import type { Palette } from './types'

const sourceUrl = 'https://unpkg.com/tailwindcss@3.4.17/lib/public/colors.js'

/** Tailwind CSS v3.4.17 colors normalized for the app. */
export const tailwindPalette = {
  id: 'tailwind',
  name: 'Tailwind CSS v3',
  sourceUrl: sourceUrl,
  groups: [
    {
      name: 'Base',
      swatches: [
        { name: 'inherit', token: '--tailwind-inherit', value: { space: 'keyword', value: 'inherit' } },
        { name: 'current', token: '--tailwind-current', value: { space: 'keyword', value: 'currentColor' } },
        { name: 'transparent', token: '--tailwind-transparent', value: { space: 'keyword', value: 'transparent' } },
        { name: 'black', token: '--tailwind-black', value: { space: 'hex', value: '#000' } },
        { name: 'white', token: '--tailwind-white', value: { space: 'hex', value: '#fff' } },
      ],
    },
    {
      name: 'Slate',
      swatches: [
        { name: 'slate-50', token: '--tailwind-slate-50', value: { space: 'hex', value: '#f8fafc' } },
        { name: 'slate-100', token: '--tailwind-slate-100', value: { space: 'hex', value: '#f1f5f9' } },
        { name: 'slate-200', token: '--tailwind-slate-200', value: { space: 'hex', value: '#e2e8f0' } },
        { name: 'slate-300', token: '--tailwind-slate-300', value: { space: 'hex', value: '#cbd5e1' } },
        { name: 'slate-400', token: '--tailwind-slate-400', value: { space: 'hex', value: '#94a3b8' } },
        { name: 'slate-500', token: '--tailwind-slate-500', value: { space: 'hex', value: '#64748b' } },
        { name: 'slate-600', token: '--tailwind-slate-600', value: { space: 'hex', value: '#475569' } },
        { name: 'slate-700', token: '--tailwind-slate-700', value: { space: 'hex', value: '#334155' } },
        { name: 'slate-800', token: '--tailwind-slate-800', value: { space: 'hex', value: '#1e293b' } },
        { name: 'slate-900', token: '--tailwind-slate-900', value: { space: 'hex', value: '#0f172a' } },
        { name: 'slate-950', token: '--tailwind-slate-950', value: { space: 'hex', value: '#020617' } },
      ],
    },
    {
      name: 'Gray',
      swatches: [
        { name: 'gray-50', token: '--tailwind-gray-50', value: { space: 'hex', value: '#f9fafb' } },
        { name: 'gray-100', token: '--tailwind-gray-100', value: { space: 'hex', value: '#f3f4f6' } },
        { name: 'gray-200', token: '--tailwind-gray-200', value: { space: 'hex', value: '#e5e7eb' } },
        { name: 'gray-300', token: '--tailwind-gray-300', value: { space: 'hex', value: '#d1d5db' } },
        { name: 'gray-400', token: '--tailwind-gray-400', value: { space: 'hex', value: '#9ca3af' } },
        { name: 'gray-500', token: '--tailwind-gray-500', value: { space: 'hex', value: '#6b7280' } },
        { name: 'gray-600', token: '--tailwind-gray-600', value: { space: 'hex', value: '#4b5563' } },
        { name: 'gray-700', token: '--tailwind-gray-700', value: { space: 'hex', value: '#374151' } },
        { name: 'gray-800', token: '--tailwind-gray-800', value: { space: 'hex', value: '#1f2937' } },
        { name: 'gray-900', token: '--tailwind-gray-900', value: { space: 'hex', value: '#111827' } },
        { name: 'gray-950', token: '--tailwind-gray-950', value: { space: 'hex', value: '#030712' } },
      ],
    },
    {
      name: 'Zinc',
      swatches: [
        { name: 'zinc-50', token: '--tailwind-zinc-50', value: { space: 'hex', value: '#fafafa' } },
        { name: 'zinc-100', token: '--tailwind-zinc-100', value: { space: 'hex', value: '#f4f4f5' } },
        { name: 'zinc-200', token: '--tailwind-zinc-200', value: { space: 'hex', value: '#e4e4e7' } },
        { name: 'zinc-300', token: '--tailwind-zinc-300', value: { space: 'hex', value: '#d4d4d8' } },
        { name: 'zinc-400', token: '--tailwind-zinc-400', value: { space: 'hex', value: '#a1a1aa' } },
        { name: 'zinc-500', token: '--tailwind-zinc-500', value: { space: 'hex', value: '#71717a' } },
        { name: 'zinc-600', token: '--tailwind-zinc-600', value: { space: 'hex', value: '#52525b' } },
        { name: 'zinc-700', token: '--tailwind-zinc-700', value: { space: 'hex', value: '#3f3f46' } },
        { name: 'zinc-800', token: '--tailwind-zinc-800', value: { space: 'hex', value: '#27272a' } },
        { name: 'zinc-900', token: '--tailwind-zinc-900', value: { space: 'hex', value: '#18181b' } },
        { name: 'zinc-950', token: '--tailwind-zinc-950', value: { space: 'hex', value: '#09090b' } },
      ],
    },
    {
      name: 'Neutral',
      swatches: [
        { name: 'neutral-50', token: '--tailwind-neutral-50', value: { space: 'hex', value: '#fafafa' } },
        { name: 'neutral-100', token: '--tailwind-neutral-100', value: { space: 'hex', value: '#f5f5f5' } },
        { name: 'neutral-200', token: '--tailwind-neutral-200', value: { space: 'hex', value: '#e5e5e5' } },
        { name: 'neutral-300', token: '--tailwind-neutral-300', value: { space: 'hex', value: '#d4d4d4' } },
        { name: 'neutral-400', token: '--tailwind-neutral-400', value: { space: 'hex', value: '#a3a3a3' } },
        { name: 'neutral-500', token: '--tailwind-neutral-500', value: { space: 'hex', value: '#737373' } },
        { name: 'neutral-600', token: '--tailwind-neutral-600', value: { space: 'hex', value: '#525252' } },
        { name: 'neutral-700', token: '--tailwind-neutral-700', value: { space: 'hex', value: '#404040' } },
        { name: 'neutral-800', token: '--tailwind-neutral-800', value: { space: 'hex', value: '#262626' } },
        { name: 'neutral-900', token: '--tailwind-neutral-900', value: { space: 'hex', value: '#171717' } },
        { name: 'neutral-950', token: '--tailwind-neutral-950', value: { space: 'hex', value: '#0a0a0a' } },
      ],
    },
    {
      name: 'Stone',
      swatches: [
        { name: 'stone-50', token: '--tailwind-stone-50', value: { space: 'hex', value: '#fafaf9' } },
        { name: 'stone-100', token: '--tailwind-stone-100', value: { space: 'hex', value: '#f5f5f4' } },
        { name: 'stone-200', token: '--tailwind-stone-200', value: { space: 'hex', value: '#e7e5e4' } },
        { name: 'stone-300', token: '--tailwind-stone-300', value: { space: 'hex', value: '#d6d3d1' } },
        { name: 'stone-400', token: '--tailwind-stone-400', value: { space: 'hex', value: '#a8a29e' } },
        { name: 'stone-500', token: '--tailwind-stone-500', value: { space: 'hex', value: '#78716c' } },
        { name: 'stone-600', token: '--tailwind-stone-600', value: { space: 'hex', value: '#57534e' } },
        { name: 'stone-700', token: '--tailwind-stone-700', value: { space: 'hex', value: '#44403c' } },
        { name: 'stone-800', token: '--tailwind-stone-800', value: { space: 'hex', value: '#292524' } },
        { name: 'stone-900', token: '--tailwind-stone-900', value: { space: 'hex', value: '#1c1917' } },
        { name: 'stone-950', token: '--tailwind-stone-950', value: { space: 'hex', value: '#0c0a09' } },
      ],
    },
    {
      name: 'Red',
      swatches: [
        { name: 'red-50', token: '--tailwind-red-50', value: { space: 'hex', value: '#fef2f2' } },
        { name: 'red-100', token: '--tailwind-red-100', value: { space: 'hex', value: '#fee2e2' } },
        { name: 'red-200', token: '--tailwind-red-200', value: { space: 'hex', value: '#fecaca' } },
        { name: 'red-300', token: '--tailwind-red-300', value: { space: 'hex', value: '#fca5a5' } },
        { name: 'red-400', token: '--tailwind-red-400', value: { space: 'hex', value: '#f87171' } },
        { name: 'red-500', token: '--tailwind-red-500', value: { space: 'hex', value: '#ef4444' } },
        { name: 'red-600', token: '--tailwind-red-600', value: { space: 'hex', value: '#dc2626' } },
        { name: 'red-700', token: '--tailwind-red-700', value: { space: 'hex', value: '#b91c1c' } },
        { name: 'red-800', token: '--tailwind-red-800', value: { space: 'hex', value: '#991b1b' } },
        { name: 'red-900', token: '--tailwind-red-900', value: { space: 'hex', value: '#7f1d1d' } },
        { name: 'red-950', token: '--tailwind-red-950', value: { space: 'hex', value: '#450a0a' } },
      ],
    },
    {
      name: 'Orange',
      swatches: [
        { name: 'orange-50', token: '--tailwind-orange-50', value: { space: 'hex', value: '#fff7ed' } },
        { name: 'orange-100', token: '--tailwind-orange-100', value: { space: 'hex', value: '#ffedd5' } },
        { name: 'orange-200', token: '--tailwind-orange-200', value: { space: 'hex', value: '#fed7aa' } },
        { name: 'orange-300', token: '--tailwind-orange-300', value: { space: 'hex', value: '#fdba74' } },
        { name: 'orange-400', token: '--tailwind-orange-400', value: { space: 'hex', value: '#fb923c' } },
        { name: 'orange-500', token: '--tailwind-orange-500', value: { space: 'hex', value: '#f97316' } },
        { name: 'orange-600', token: '--tailwind-orange-600', value: { space: 'hex', value: '#ea580c' } },
        { name: 'orange-700', token: '--tailwind-orange-700', value: { space: 'hex', value: '#c2410c' } },
        { name: 'orange-800', token: '--tailwind-orange-800', value: { space: 'hex', value: '#9a3412' } },
        { name: 'orange-900', token: '--tailwind-orange-900', value: { space: 'hex', value: '#7c2d12' } },
        { name: 'orange-950', token: '--tailwind-orange-950', value: { space: 'hex', value: '#431407' } },
      ],
    },
    {
      name: 'Amber',
      swatches: [
        { name: 'amber-50', token: '--tailwind-amber-50', value: { space: 'hex', value: '#fffbeb' } },
        { name: 'amber-100', token: '--tailwind-amber-100', value: { space: 'hex', value: '#fef3c7' } },
        { name: 'amber-200', token: '--tailwind-amber-200', value: { space: 'hex', value: '#fde68a' } },
        { name: 'amber-300', token: '--tailwind-amber-300', value: { space: 'hex', value: '#fcd34d' } },
        { name: 'amber-400', token: '--tailwind-amber-400', value: { space: 'hex', value: '#fbbf24' } },
        { name: 'amber-500', token: '--tailwind-amber-500', value: { space: 'hex', value: '#f59e0b' } },
        { name: 'amber-600', token: '--tailwind-amber-600', value: { space: 'hex', value: '#d97706' } },
        { name: 'amber-700', token: '--tailwind-amber-700', value: { space: 'hex', value: '#b45309' } },
        { name: 'amber-800', token: '--tailwind-amber-800', value: { space: 'hex', value: '#92400e' } },
        { name: 'amber-900', token: '--tailwind-amber-900', value: { space: 'hex', value: '#78350f' } },
        { name: 'amber-950', token: '--tailwind-amber-950', value: { space: 'hex', value: '#451a03' } },
      ],
    },
    {
      name: 'Yellow',
      swatches: [
        { name: 'yellow-50', token: '--tailwind-yellow-50', value: { space: 'hex', value: '#fefce8' } },
        { name: 'yellow-100', token: '--tailwind-yellow-100', value: { space: 'hex', value: '#fef9c3' } },
        { name: 'yellow-200', token: '--tailwind-yellow-200', value: { space: 'hex', value: '#fef08a' } },
        { name: 'yellow-300', token: '--tailwind-yellow-300', value: { space: 'hex', value: '#fde047' } },
        { name: 'yellow-400', token: '--tailwind-yellow-400', value: { space: 'hex', value: '#facc15' } },
        { name: 'yellow-500', token: '--tailwind-yellow-500', value: { space: 'hex', value: '#eab308' } },
        { name: 'yellow-600', token: '--tailwind-yellow-600', value: { space: 'hex', value: '#ca8a04' } },
        { name: 'yellow-700', token: '--tailwind-yellow-700', value: { space: 'hex', value: '#a16207' } },
        { name: 'yellow-800', token: '--tailwind-yellow-800', value: { space: 'hex', value: '#854d0e' } },
        { name: 'yellow-900', token: '--tailwind-yellow-900', value: { space: 'hex', value: '#713f12' } },
        { name: 'yellow-950', token: '--tailwind-yellow-950', value: { space: 'hex', value: '#422006' } },
      ],
    },
    {
      name: 'Lime',
      swatches: [
        { name: 'lime-50', token: '--tailwind-lime-50', value: { space: 'hex', value: '#f7fee7' } },
        { name: 'lime-100', token: '--tailwind-lime-100', value: { space: 'hex', value: '#ecfccb' } },
        { name: 'lime-200', token: '--tailwind-lime-200', value: { space: 'hex', value: '#d9f99d' } },
        { name: 'lime-300', token: '--tailwind-lime-300', value: { space: 'hex', value: '#bef264' } },
        { name: 'lime-400', token: '--tailwind-lime-400', value: { space: 'hex', value: '#a3e635' } },
        { name: 'lime-500', token: '--tailwind-lime-500', value: { space: 'hex', value: '#84cc16' } },
        { name: 'lime-600', token: '--tailwind-lime-600', value: { space: 'hex', value: '#65a30d' } },
        { name: 'lime-700', token: '--tailwind-lime-700', value: { space: 'hex', value: '#4d7c0f' } },
        { name: 'lime-800', token: '--tailwind-lime-800', value: { space: 'hex', value: '#3f6212' } },
        { name: 'lime-900', token: '--tailwind-lime-900', value: { space: 'hex', value: '#365314' } },
        { name: 'lime-950', token: '--tailwind-lime-950', value: { space: 'hex', value: '#1a2e05' } },
      ],
    },
    {
      name: 'Green',
      swatches: [
        { name: 'green-50', token: '--tailwind-green-50', value: { space: 'hex', value: '#f0fdf4' } },
        { name: 'green-100', token: '--tailwind-green-100', value: { space: 'hex', value: '#dcfce7' } },
        { name: 'green-200', token: '--tailwind-green-200', value: { space: 'hex', value: '#bbf7d0' } },
        { name: 'green-300', token: '--tailwind-green-300', value: { space: 'hex', value: '#86efac' } },
        { name: 'green-400', token: '--tailwind-green-400', value: { space: 'hex', value: '#4ade80' } },
        { name: 'green-500', token: '--tailwind-green-500', value: { space: 'hex', value: '#22c55e' } },
        { name: 'green-600', token: '--tailwind-green-600', value: { space: 'hex', value: '#16a34a' } },
        { name: 'green-700', token: '--tailwind-green-700', value: { space: 'hex', value: '#15803d' } },
        { name: 'green-800', token: '--tailwind-green-800', value: { space: 'hex', value: '#166534' } },
        { name: 'green-900', token: '--tailwind-green-900', value: { space: 'hex', value: '#14532d' } },
        { name: 'green-950', token: '--tailwind-green-950', value: { space: 'hex', value: '#052e16' } },
      ],
    },
    {
      name: 'Emerald',
      swatches: [
        { name: 'emerald-50', token: '--tailwind-emerald-50', value: { space: 'hex', value: '#ecfdf5' } },
        { name: 'emerald-100', token: '--tailwind-emerald-100', value: { space: 'hex', value: '#d1fae5' } },
        { name: 'emerald-200', token: '--tailwind-emerald-200', value: { space: 'hex', value: '#a7f3d0' } },
        { name: 'emerald-300', token: '--tailwind-emerald-300', value: { space: 'hex', value: '#6ee7b7' } },
        { name: 'emerald-400', token: '--tailwind-emerald-400', value: { space: 'hex', value: '#34d399' } },
        { name: 'emerald-500', token: '--tailwind-emerald-500', value: { space: 'hex', value: '#10b981' } },
        { name: 'emerald-600', token: '--tailwind-emerald-600', value: { space: 'hex', value: '#059669' } },
        { name: 'emerald-700', token: '--tailwind-emerald-700', value: { space: 'hex', value: '#047857' } },
        { name: 'emerald-800', token: '--tailwind-emerald-800', value: { space: 'hex', value: '#065f46' } },
        { name: 'emerald-900', token: '--tailwind-emerald-900', value: { space: 'hex', value: '#064e3b' } },
        { name: 'emerald-950', token: '--tailwind-emerald-950', value: { space: 'hex', value: '#022c22' } },
      ],
    },
    {
      name: 'Teal',
      swatches: [
        { name: 'teal-50', token: '--tailwind-teal-50', value: { space: 'hex', value: '#f0fdfa' } },
        { name: 'teal-100', token: '--tailwind-teal-100', value: { space: 'hex', value: '#ccfbf1' } },
        { name: 'teal-200', token: '--tailwind-teal-200', value: { space: 'hex', value: '#99f6e4' } },
        { name: 'teal-300', token: '--tailwind-teal-300', value: { space: 'hex', value: '#5eead4' } },
        { name: 'teal-400', token: '--tailwind-teal-400', value: { space: 'hex', value: '#2dd4bf' } },
        { name: 'teal-500', token: '--tailwind-teal-500', value: { space: 'hex', value: '#14b8a6' } },
        { name: 'teal-600', token: '--tailwind-teal-600', value: { space: 'hex', value: '#0d9488' } },
        { name: 'teal-700', token: '--tailwind-teal-700', value: { space: 'hex', value: '#0f766e' } },
        { name: 'teal-800', token: '--tailwind-teal-800', value: { space: 'hex', value: '#115e59' } },
        { name: 'teal-900', token: '--tailwind-teal-900', value: { space: 'hex', value: '#134e4a' } },
        { name: 'teal-950', token: '--tailwind-teal-950', value: { space: 'hex', value: '#042f2e' } },
      ],
    },
    {
      name: 'Cyan',
      swatches: [
        { name: 'cyan-50', token: '--tailwind-cyan-50', value: { space: 'hex', value: '#ecfeff' } },
        { name: 'cyan-100', token: '--tailwind-cyan-100', value: { space: 'hex', value: '#cffafe' } },
        { name: 'cyan-200', token: '--tailwind-cyan-200', value: { space: 'hex', value: '#a5f3fc' } },
        { name: 'cyan-300', token: '--tailwind-cyan-300', value: { space: 'hex', value: '#67e8f9' } },
        { name: 'cyan-400', token: '--tailwind-cyan-400', value: { space: 'hex', value: '#22d3ee' } },
        { name: 'cyan-500', token: '--tailwind-cyan-500', value: { space: 'hex', value: '#06b6d4' } },
        { name: 'cyan-600', token: '--tailwind-cyan-600', value: { space: 'hex', value: '#0891b2' } },
        { name: 'cyan-700', token: '--tailwind-cyan-700', value: { space: 'hex', value: '#0e7490' } },
        { name: 'cyan-800', token: '--tailwind-cyan-800', value: { space: 'hex', value: '#155e75' } },
        { name: 'cyan-900', token: '--tailwind-cyan-900', value: { space: 'hex', value: '#164e63' } },
        { name: 'cyan-950', token: '--tailwind-cyan-950', value: { space: 'hex', value: '#083344' } },
      ],
    },
    {
      name: 'Sky',
      swatches: [
        { name: 'sky-50', token: '--tailwind-sky-50', value: { space: 'hex', value: '#f0f9ff' } },
        { name: 'sky-100', token: '--tailwind-sky-100', value: { space: 'hex', value: '#e0f2fe' } },
        { name: 'sky-200', token: '--tailwind-sky-200', value: { space: 'hex', value: '#bae6fd' } },
        { name: 'sky-300', token: '--tailwind-sky-300', value: { space: 'hex', value: '#7dd3fc' } },
        { name: 'sky-400', token: '--tailwind-sky-400', value: { space: 'hex', value: '#38bdf8' } },
        { name: 'sky-500', token: '--tailwind-sky-500', value: { space: 'hex', value: '#0ea5e9' } },
        { name: 'sky-600', token: '--tailwind-sky-600', value: { space: 'hex', value: '#0284c7' } },
        { name: 'sky-700', token: '--tailwind-sky-700', value: { space: 'hex', value: '#0369a1' } },
        { name: 'sky-800', token: '--tailwind-sky-800', value: { space: 'hex', value: '#075985' } },
        { name: 'sky-900', token: '--tailwind-sky-900', value: { space: 'hex', value: '#0c4a6e' } },
        { name: 'sky-950', token: '--tailwind-sky-950', value: { space: 'hex', value: '#082f49' } },
      ],
    },
    {
      name: 'Blue',
      swatches: [
        { name: 'blue-50', token: '--tailwind-blue-50', value: { space: 'hex', value: '#eff6ff' } },
        { name: 'blue-100', token: '--tailwind-blue-100', value: { space: 'hex', value: '#dbeafe' } },
        { name: 'blue-200', token: '--tailwind-blue-200', value: { space: 'hex', value: '#bfdbfe' } },
        { name: 'blue-300', token: '--tailwind-blue-300', value: { space: 'hex', value: '#93c5fd' } },
        { name: 'blue-400', token: '--tailwind-blue-400', value: { space: 'hex', value: '#60a5fa' } },
        { name: 'blue-500', token: '--tailwind-blue-500', value: { space: 'hex', value: '#3b82f6' } },
        { name: 'blue-600', token: '--tailwind-blue-600', value: { space: 'hex', value: '#2563eb' } },
        { name: 'blue-700', token: '--tailwind-blue-700', value: { space: 'hex', value: '#1d4ed8' } },
        { name: 'blue-800', token: '--tailwind-blue-800', value: { space: 'hex', value: '#1e40af' } },
        { name: 'blue-900', token: '--tailwind-blue-900', value: { space: 'hex', value: '#1e3a8a' } },
        { name: 'blue-950', token: '--tailwind-blue-950', value: { space: 'hex', value: '#172554' } },
      ],
    },
    {
      name: 'Indigo',
      swatches: [
        { name: 'indigo-50', token: '--tailwind-indigo-50', value: { space: 'hex', value: '#eef2ff' } },
        { name: 'indigo-100', token: '--tailwind-indigo-100', value: { space: 'hex', value: '#e0e7ff' } },
        { name: 'indigo-200', token: '--tailwind-indigo-200', value: { space: 'hex', value: '#c7d2fe' } },
        { name: 'indigo-300', token: '--tailwind-indigo-300', value: { space: 'hex', value: '#a5b4fc' } },
        { name: 'indigo-400', token: '--tailwind-indigo-400', value: { space: 'hex', value: '#818cf8' } },
        { name: 'indigo-500', token: '--tailwind-indigo-500', value: { space: 'hex', value: '#6366f1' } },
        { name: 'indigo-600', token: '--tailwind-indigo-600', value: { space: 'hex', value: '#4f46e5' } },
        { name: 'indigo-700', token: '--tailwind-indigo-700', value: { space: 'hex', value: '#4338ca' } },
        { name: 'indigo-800', token: '--tailwind-indigo-800', value: { space: 'hex', value: '#3730a3' } },
        { name: 'indigo-900', token: '--tailwind-indigo-900', value: { space: 'hex', value: '#312e81' } },
        { name: 'indigo-950', token: '--tailwind-indigo-950', value: { space: 'hex', value: '#1e1b4b' } },
      ],
    },
    {
      name: 'Violet',
      swatches: [
        { name: 'violet-50', token: '--tailwind-violet-50', value: { space: 'hex', value: '#f5f3ff' } },
        { name: 'violet-100', token: '--tailwind-violet-100', value: { space: 'hex', value: '#ede9fe' } },
        { name: 'violet-200', token: '--tailwind-violet-200', value: { space: 'hex', value: '#ddd6fe' } },
        { name: 'violet-300', token: '--tailwind-violet-300', value: { space: 'hex', value: '#c4b5fd' } },
        { name: 'violet-400', token: '--tailwind-violet-400', value: { space: 'hex', value: '#a78bfa' } },
        { name: 'violet-500', token: '--tailwind-violet-500', value: { space: 'hex', value: '#8b5cf6' } },
        { name: 'violet-600', token: '--tailwind-violet-600', value: { space: 'hex', value: '#7c3aed' } },
        { name: 'violet-700', token: '--tailwind-violet-700', value: { space: 'hex', value: '#6d28d9' } },
        { name: 'violet-800', token: '--tailwind-violet-800', value: { space: 'hex', value: '#5b21b6' } },
        { name: 'violet-900', token: '--tailwind-violet-900', value: { space: 'hex', value: '#4c1d95' } },
        { name: 'violet-950', token: '--tailwind-violet-950', value: { space: 'hex', value: '#2e1065' } },
      ],
    },
    {
      name: 'Purple',
      swatches: [
        { name: 'purple-50', token: '--tailwind-purple-50', value: { space: 'hex', value: '#faf5ff' } },
        { name: 'purple-100', token: '--tailwind-purple-100', value: { space: 'hex', value: '#f3e8ff' } },
        { name: 'purple-200', token: '--tailwind-purple-200', value: { space: 'hex', value: '#e9d5ff' } },
        { name: 'purple-300', token: '--tailwind-purple-300', value: { space: 'hex', value: '#d8b4fe' } },
        { name: 'purple-400', token: '--tailwind-purple-400', value: { space: 'hex', value: '#c084fc' } },
        { name: 'purple-500', token: '--tailwind-purple-500', value: { space: 'hex', value: '#a855f7' } },
        { name: 'purple-600', token: '--tailwind-purple-600', value: { space: 'hex', value: '#9333ea' } },
        { name: 'purple-700', token: '--tailwind-purple-700', value: { space: 'hex', value: '#7e22ce' } },
        { name: 'purple-800', token: '--tailwind-purple-800', value: { space: 'hex', value: '#6b21a8' } },
        { name: 'purple-900', token: '--tailwind-purple-900', value: { space: 'hex', value: '#581c87' } },
        { name: 'purple-950', token: '--tailwind-purple-950', value: { space: 'hex', value: '#3b0764' } },
      ],
    },
    {
      name: 'Fuchsia',
      swatches: [
        { name: 'fuchsia-50', token: '--tailwind-fuchsia-50', value: { space: 'hex', value: '#fdf4ff' } },
        { name: 'fuchsia-100', token: '--tailwind-fuchsia-100', value: { space: 'hex', value: '#fae8ff' } },
        { name: 'fuchsia-200', token: '--tailwind-fuchsia-200', value: { space: 'hex', value: '#f5d0fe' } },
        { name: 'fuchsia-300', token: '--tailwind-fuchsia-300', value: { space: 'hex', value: '#f0abfc' } },
        { name: 'fuchsia-400', token: '--tailwind-fuchsia-400', value: { space: 'hex', value: '#e879f9' } },
        { name: 'fuchsia-500', token: '--tailwind-fuchsia-500', value: { space: 'hex', value: '#d946ef' } },
        { name: 'fuchsia-600', token: '--tailwind-fuchsia-600', value: { space: 'hex', value: '#c026d3' } },
        { name: 'fuchsia-700', token: '--tailwind-fuchsia-700', value: { space: 'hex', value: '#a21caf' } },
        { name: 'fuchsia-800', token: '--tailwind-fuchsia-800', value: { space: 'hex', value: '#86198f' } },
        { name: 'fuchsia-900', token: '--tailwind-fuchsia-900', value: { space: 'hex', value: '#701a75' } },
        { name: 'fuchsia-950', token: '--tailwind-fuchsia-950', value: { space: 'hex', value: '#4a044e' } },
      ],
    },
    {
      name: 'Pink',
      swatches: [
        { name: 'pink-50', token: '--tailwind-pink-50', value: { space: 'hex', value: '#fdf2f8' } },
        { name: 'pink-100', token: '--tailwind-pink-100', value: { space: 'hex', value: '#fce7f3' } },
        { name: 'pink-200', token: '--tailwind-pink-200', value: { space: 'hex', value: '#fbcfe8' } },
        { name: 'pink-300', token: '--tailwind-pink-300', value: { space: 'hex', value: '#f9a8d4' } },
        { name: 'pink-400', token: '--tailwind-pink-400', value: { space: 'hex', value: '#f472b6' } },
        { name: 'pink-500', token: '--tailwind-pink-500', value: { space: 'hex', value: '#ec4899' } },
        { name: 'pink-600', token: '--tailwind-pink-600', value: { space: 'hex', value: '#db2777' } },
        { name: 'pink-700', token: '--tailwind-pink-700', value: { space: 'hex', value: '#be185d' } },
        { name: 'pink-800', token: '--tailwind-pink-800', value: { space: 'hex', value: '#9d174d' } },
        { name: 'pink-900', token: '--tailwind-pink-900', value: { space: 'hex', value: '#831843' } },
        { name: 'pink-950', token: '--tailwind-pink-950', value: { space: 'hex', value: '#500724' } },
      ],
    },
    {
      name: 'Rose',
      swatches: [
        { name: 'rose-50', token: '--tailwind-rose-50', value: { space: 'hex', value: '#fff1f2' } },
        { name: 'rose-100', token: '--tailwind-rose-100', value: { space: 'hex', value: '#ffe4e6' } },
        { name: 'rose-200', token: '--tailwind-rose-200', value: { space: 'hex', value: '#fecdd3' } },
        { name: 'rose-300', token: '--tailwind-rose-300', value: { space: 'hex', value: '#fda4af' } },
        { name: 'rose-400', token: '--tailwind-rose-400', value: { space: 'hex', value: '#fb7185' } },
        { name: 'rose-500', token: '--tailwind-rose-500', value: { space: 'hex', value: '#f43f5e' } },
        { name: 'rose-600', token: '--tailwind-rose-600', value: { space: 'hex', value: '#e11d48' } },
        { name: 'rose-700', token: '--tailwind-rose-700', value: { space: 'hex', value: '#be123c' } },
        { name: 'rose-800', token: '--tailwind-rose-800', value: { space: 'hex', value: '#9f1239' } },
        { name: 'rose-900', token: '--tailwind-rose-900', value: { space: 'hex', value: '#881337' } },
        { name: 'rose-950', token: '--tailwind-rose-950', value: { space: 'hex', value: '#4c0519' } },
      ],
    },
  ],
} satisfies Palette
