import type { Palette } from './types'

const sourceUrl = 'https://designsystem.digital.gov/design-tokens/color/system-tokens/'

/** USWDS colors normalized from upstream design tokens. */
export const uswdsPalette = {
  id: 'uswds',
  name: 'USWDS',
  sourceUrl: sourceUrl,
  groups: [
    {
      name: 'Base',
      swatches: [
        { name: 'transparent', token: '--uswds-transparent', value: { space: 'keyword', value: 'transparent' } },
        { name: 'black', token: '--uswds-black', value: { space: 'hex', value: '#000' } },
        { name: 'white', token: '--uswds-white', value: { space: 'hex', value: '#fff' } },
      ],
    },
    {
      name: 'Red Cool',
      swatches: [
        { name: 'red-cool-5', token: '--uswds-red-cool-5', value: { space: 'hex', value: '#f8eff1' } },
        { name: 'red-cool-10', token: '--uswds-red-cool-10', value: { space: 'hex', value: '#f3e1e4' } },
        { name: 'red-cool-20', token: '--uswds-red-cool-20', value: { space: 'hex', value: '#ecbec6' } },
        { name: 'red-cool-30', token: '--uswds-red-cool-30', value: { space: 'hex', value: '#e09aa6' } },
        { name: 'red-cool-40', token: '--uswds-red-cool-40', value: { space: 'hex', value: '#e16b80' } },
        { name: 'red-cool-50', token: '--uswds-red-cool-50', value: { space: 'hex', value: '#cd425b' } },
        { name: 'red-cool-60', token: '--uswds-red-cool-60', value: { space: 'hex', value: '#9e394b' } },
        { name: 'red-cool-70', token: '--uswds-red-cool-70', value: { space: 'hex', value: '#68363f' } },
        { name: 'red-cool-80', token: '--uswds-red-cool-80', value: { space: 'hex', value: '#40282c' } },
        { name: 'red-cool-90', token: '--uswds-red-cool-90', value: { space: 'hex', value: '#1e1517' } },
        { name: 'red-cool-5v', token: '--uswds-red-cool-5v', value: { space: 'hex', value: '#fff2f5' } },
        { name: 'red-cool-10v', token: '--uswds-red-cool-10v', value: { space: 'hex', value: '#f8dfe2' } },
        { name: 'red-cool-20v', token: '--uswds-red-cool-20v', value: { space: 'hex', value: '#f8b9c5' } },
        { name: 'red-cool-30v', token: '--uswds-red-cool-30v', value: { space: 'hex', value: '#fd8ba0' } },
        { name: 'red-cool-40v', token: '--uswds-red-cool-40v', value: { space: 'hex', value: '#f45d79' } },
        { name: 'red-cool-50v', token: '--uswds-red-cool-50v', value: { space: 'hex', value: '#e41d3d' } },
        { name: 'red-cool-60v', token: '--uswds-red-cool-60v', value: { space: 'hex', value: '#b21d38' } },
        { name: 'red-cool-70v', token: '--uswds-red-cool-70v', value: { space: 'hex', value: '#822133' } },
        { name: 'red-cool-80v', token: '--uswds-red-cool-80v', value: { space: 'hex', value: '#4f1c24' } },
      ],
    },
    {
      name: 'Red',
      swatches: [
        { name: 'red-5', token: '--uswds-red-5', value: { space: 'hex', value: '#f9eeee' } },
        { name: 'red-10', token: '--uswds-red-10', value: { space: 'hex', value: '#f8e1de' } },
        { name: 'red-20', token: '--uswds-red-20', value: { space: 'hex', value: '#f7bbb1' } },
        { name: 'red-30', token: '--uswds-red-30', value: { space: 'hex', value: '#f2938c' } },
        { name: 'red-40', token: '--uswds-red-40', value: { space: 'hex', value: '#e9695f' } },
        { name: 'red-50', token: '--uswds-red-50', value: { space: 'hex', value: '#d83933' } },
        { name: 'red-60', token: '--uswds-red-60', value: { space: 'hex', value: '#a23737' } },
        { name: 'red-70', token: '--uswds-red-70', value: { space: 'hex', value: '#6f3331' } },
        { name: 'red-80', token: '--uswds-red-80', value: { space: 'hex', value: '#3e2927' } },
        { name: 'red-90', token: '--uswds-red-90', value: { space: 'hex', value: '#1b1616' } },
        { name: 'red-5v', token: '--uswds-red-5v', value: { space: 'hex', value: '#fff3f2' } },
        { name: 'red-10v', token: '--uswds-red-10v', value: { space: 'hex', value: '#fde0db' } },
        { name: 'red-20v', token: '--uswds-red-20v', value: { space: 'hex', value: '#fdb8ae' } },
        { name: 'red-30v', token: '--uswds-red-30v', value: { space: 'hex', value: '#ff8d7b' } },
        { name: 'red-40v', token: '--uswds-red-40v', value: { space: 'hex', value: '#fb5a47' } },
        { name: 'red-50v', token: '--uswds-red-50v', value: { space: 'hex', value: '#e52207' } },
        { name: 'red-60v', token: '--uswds-red-60v', value: { space: 'hex', value: '#b50909' } },
        { name: 'red-70v', token: '--uswds-red-70v', value: { space: 'hex', value: '#8b0a03' } },
        { name: 'red-80v', token: '--uswds-red-80v', value: { space: 'hex', value: '#5c1111' } },
      ],
    },
    {
      name: 'Red Warm',
      swatches: [
        { name: 'red-warm-5', token: '--uswds-red-warm-5', value: { space: 'hex', value: '#f6efea' } },
        { name: 'red-warm-10', token: '--uswds-red-warm-10', value: { space: 'hex', value: '#f4e3db' } },
        { name: 'red-warm-20', token: '--uswds-red-warm-20', value: { space: 'hex', value: '#ecc0a7' } },
        { name: 'red-warm-30', token: '--uswds-red-warm-30', value: { space: 'hex', value: '#dca081' } },
        { name: 'red-warm-40', token: '--uswds-red-warm-40', value: { space: 'hex', value: '#d27a56' } },
        { name: 'red-warm-50', token: '--uswds-red-warm-50', value: { space: 'hex', value: '#c3512c' } },
        { name: 'red-warm-60', token: '--uswds-red-warm-60', value: { space: 'hex', value: '#805039' } },
        { name: 'red-warm-70', token: '--uswds-red-warm-70', value: { space: 'hex', value: '#524236' } },
        { name: 'red-warm-80', token: '--uswds-red-warm-80', value: { space: 'hex', value: '#332d29' } },
        { name: 'red-warm-90', token: '--uswds-red-warm-90', value: { space: 'hex', value: '#1f1c18' } },
        { name: 'red-warm-5v', token: '--uswds-red-warm-5v', value: { space: 'hex', value: '#fff5ee' } },
        { name: 'red-warm-10v', token: '--uswds-red-warm-10v', value: { space: 'hex', value: '#fce1d4' } },
        { name: 'red-warm-20v', token: '--uswds-red-warm-20v', value: { space: 'hex', value: '#f6bd9c' } },
        { name: 'red-warm-30v', token: '--uswds-red-warm-30v', value: { space: 'hex', value: '#f39268' } },
        { name: 'red-warm-40v', token: '--uswds-red-warm-40v', value: { space: 'hex', value: '#ef5e25' } },
        { name: 'red-warm-50v', token: '--uswds-red-warm-50v', value: { space: 'hex', value: '#d54309' } },
        { name: 'red-warm-60v', token: '--uswds-red-warm-60v', value: { space: 'hex', value: '#9c3d10' } },
        { name: 'red-warm-70v', token: '--uswds-red-warm-70v', value: { space: 'hex', value: '#63340f' } },
        { name: 'red-warm-80v', token: '--uswds-red-warm-80v', value: { space: 'hex', value: '#3e2a1e' } },
      ],
    },
    {
      name: 'Orange Warm',
      swatches: [
        { name: 'orange-warm-5', token: '--uswds-orange-warm-5', value: { space: 'hex', value: '#faeee5' } },
        { name: 'orange-warm-10', token: '--uswds-orange-warm-10', value: { space: 'hex', value: '#fbe0d0' } },
        { name: 'orange-warm-20', token: '--uswds-orange-warm-20', value: { space: 'hex', value: '#f7bca2' } },
        { name: 'orange-warm-30', token: '--uswds-orange-warm-30', value: { space: 'hex', value: '#f3966d' } },
        { name: 'orange-warm-40', token: '--uswds-orange-warm-40', value: { space: 'hex', value: '#e17141' } },
        { name: 'orange-warm-50', token: '--uswds-orange-warm-50', value: { space: 'hex', value: '#bd5727' } },
        { name: 'orange-warm-60', token: '--uswds-orange-warm-60', value: { space: 'hex', value: '#914734' } },
        { name: 'orange-warm-70', token: '--uswds-orange-warm-70', value: { space: 'hex', value: '#633a32' } },
        { name: 'orange-warm-80', token: '--uswds-orange-warm-80', value: { space: 'hex', value: '#3d2925' } },
        { name: 'orange-warm-90', token: '--uswds-orange-warm-90', value: { space: 'hex', value: '#1c1615' } },
        { name: 'orange-warm-5v', token: '--uswds-orange-warm-5v', value: { space: 'hex', value: '#fff3ea' } },
        { name: 'orange-warm-10v', token: '--uswds-orange-warm-10v', value: { space: 'hex', value: '#ffe2d1' } },
        { name: 'orange-warm-20v', token: '--uswds-orange-warm-20v', value: { space: 'hex', value: '#fbbaa7' } },
        { name: 'orange-warm-30v', token: '--uswds-orange-warm-30v', value: { space: 'hex', value: '#fc906d' } },
        { name: 'orange-warm-40v', token: '--uswds-orange-warm-40v', value: { space: 'hex', value: '#ff580a' } },
        { name: 'orange-warm-50v', token: '--uswds-orange-warm-50v', value: { space: 'hex', value: '#cf4900' } },
        { name: 'orange-warm-60v', token: '--uswds-orange-warm-60v', value: { space: 'hex', value: '#a72f10' } },
        { name: 'orange-warm-70v', token: '--uswds-orange-warm-70v', value: { space: 'hex', value: '#782312' } },
        { name: 'orange-warm-80v', token: '--uswds-orange-warm-80v', value: { space: 'hex', value: '#3d231d' } },
      ],
    },
    {
      name: 'Orange',
      swatches: [
        { name: 'orange-5', token: '--uswds-orange-5', value: { space: 'hex', value: '#f6efe9' } },
        { name: 'orange-10', token: '--uswds-orange-10', value: { space: 'hex', value: '#f2e4d4' } },
        { name: 'orange-20', token: '--uswds-orange-20', value: { space: 'hex', value: '#f3bf90' } },
        { name: 'orange-30', token: '--uswds-orange-30', value: { space: 'hex', value: '#f09860' } },
        { name: 'orange-40', token: '--uswds-orange-40', value: { space: 'hex', value: '#dd7533' } },
        { name: 'orange-50', token: '--uswds-orange-50', value: { space: 'hex', value: '#a86437' } },
        { name: 'orange-60', token: '--uswds-orange-60', value: { space: 'hex', value: '#775540' } },
        { name: 'orange-70', token: '--uswds-orange-70', value: { space: 'hex', value: '#524236' } },
        { name: 'orange-80', token: '--uswds-orange-80', value: { space: 'hex', value: '#332d27' } },
        { name: 'orange-90', token: '--uswds-orange-90', value: { space: 'hex', value: '#1b1614' } },
        { name: 'orange-5v', token: '--uswds-orange-5v', value: { space: 'hex', value: '#fef2e4' } },
        { name: 'orange-10v', token: '--uswds-orange-10v', value: { space: 'hex', value: '#fce2c5' } },
        { name: 'orange-20v', token: '--uswds-orange-20v', value: { space: 'hex', value: '#ffbc78' } },
        { name: 'orange-30v', token: '--uswds-orange-30v', value: { space: 'hex', value: '#fa9441' } },
        { name: 'orange-40v', token: '--uswds-orange-40v', value: { space: 'hex', value: '#e66f0e' } },
        { name: 'orange-50v', token: '--uswds-orange-50v', value: { space: 'hex', value: '#c05600' } },
        { name: 'orange-60v', token: '--uswds-orange-60v', value: { space: 'hex', value: '#8c471c' } },
        { name: 'orange-70v', token: '--uswds-orange-70v', value: { space: 'hex', value: '#5f3617' } },
        { name: 'orange-80v', token: '--uswds-orange-80v', value: { space: 'hex', value: '#352313' } },
      ],
    },
    {
      name: 'Gold',
      swatches: [
        { name: 'gold-5', token: '--uswds-gold-5', value: { space: 'hex', value: '#f5f0e6' } },
        { name: 'gold-10', token: '--uswds-gold-10', value: { space: 'hex', value: '#f1e5cd' } },
        { name: 'gold-20', token: '--uswds-gold-20', value: { space: 'hex', value: '#dec69a' } },
        { name: 'gold-30', token: '--uswds-gold-30', value: { space: 'hex', value: '#c7a97b' } },
        { name: 'gold-40', token: '--uswds-gold-40', value: { space: 'hex', value: '#ad8b65' } },
        { name: 'gold-50', token: '--uswds-gold-50', value: { space: 'hex', value: '#8e704f' } },
        { name: 'gold-60', token: '--uswds-gold-60', value: { space: 'hex', value: '#6b5947' } },
        { name: 'gold-70', token: '--uswds-gold-70', value: { space: 'hex', value: '#4d4438' } },
        { name: 'gold-80', token: '--uswds-gold-80', value: { space: 'hex', value: '#322d26' } },
        { name: 'gold-90', token: '--uswds-gold-90', value: { space: 'hex', value: '#191714' } },
        { name: 'gold-5v', token: '--uswds-gold-5v', value: { space: 'hex', value: '#fef0c8' } },
        { name: 'gold-10v', token: '--uswds-gold-10v', value: { space: 'hex', value: '#ffe396' } },
        { name: 'gold-20v', token: '--uswds-gold-20v', value: { space: 'hex', value: '#ffbe2e' } },
        { name: 'gold-30v', token: '--uswds-gold-30v', value: { space: 'hex', value: '#e5a000' } },
        { name: 'gold-40v', token: '--uswds-gold-40v', value: { space: 'hex', value: '#c2850c' } },
        { name: 'gold-50v', token: '--uswds-gold-50v', value: { space: 'hex', value: '#936f38' } },
        { name: 'gold-60v', token: '--uswds-gold-60v', value: { space: 'hex', value: '#7a591a' } },
        { name: 'gold-70v', token: '--uswds-gold-70v', value: { space: 'hex', value: '#5c410a' } },
        { name: 'gold-80v', token: '--uswds-gold-80v', value: { space: 'hex', value: '#3b2b15' } },
      ],
    },
    {
      name: 'Yellow',
      swatches: [
        { name: 'yellow-5', token: '--uswds-yellow-5', value: { space: 'hex', value: '#faf3d1' } },
        { name: 'yellow-10', token: '--uswds-yellow-10', value: { space: 'hex', value: '#f5e6af' } },
        { name: 'yellow-20', token: '--uswds-yellow-20', value: { space: 'hex', value: '#e6c74c' } },
        { name: 'yellow-30', token: '--uswds-yellow-30', value: { space: 'hex', value: '#c9ab48' } },
        { name: 'yellow-40', token: '--uswds-yellow-40', value: { space: 'hex', value: '#a88f48' } },
        { name: 'yellow-50', token: '--uswds-yellow-50', value: { space: 'hex', value: '#8a7237' } },
        { name: 'yellow-60', token: '--uswds-yellow-60', value: { space: 'hex', value: '#6b5a39' } },
        { name: 'yellow-70', token: '--uswds-yellow-70', value: { space: 'hex', value: '#504332' } },
        { name: 'yellow-80', token: '--uswds-yellow-80', value: { space: 'hex', value: '#332d27' } },
        { name: 'yellow-90', token: '--uswds-yellow-90', value: { space: 'hex', value: '#1a1614' } },
        { name: 'yellow-5v', token: '--uswds-yellow-5v', value: { space: 'hex', value: '#fff5c2' } },
        { name: 'yellow-10v', token: '--uswds-yellow-10v', value: { space: 'hex', value: '#fee685' } },
        { name: 'yellow-20v', token: '--uswds-yellow-20v', value: { space: 'hex', value: '#face00' } },
        { name: 'yellow-30v', token: '--uswds-yellow-30v', value: { space: 'hex', value: '#ddaa01' } },
        { name: 'yellow-40v', token: '--uswds-yellow-40v', value: { space: 'hex', value: '#b38c00' } },
        { name: 'yellow-50v', token: '--uswds-yellow-50v', value: { space: 'hex', value: '#947100' } },
        { name: 'yellow-60v', token: '--uswds-yellow-60v', value: { space: 'hex', value: '#776017' } },
        { name: 'yellow-70v', token: '--uswds-yellow-70v', value: { space: 'hex', value: '#5c4809' } },
        { name: 'yellow-80v', token: '--uswds-yellow-80v', value: { space: 'hex', value: '#422d19' } },
      ],
    },
    {
      name: 'Green Warm',
      swatches: [
        { name: 'green-warm-5', token: '--uswds-green-warm-5', value: { space: 'hex', value: '#f1f4d7' } },
        { name: 'green-warm-10', token: '--uswds-green-warm-10', value: { space: 'hex', value: '#e7eab7' } },
        { name: 'green-warm-20', token: '--uswds-green-warm-20', value: { space: 'hex', value: '#cbd17a' } },
        { name: 'green-warm-30', token: '--uswds-green-warm-30', value: { space: 'hex', value: '#a6b557' } },
        { name: 'green-warm-40', token: '--uswds-green-warm-40', value: { space: 'hex', value: '#8a984b' } },
        { name: 'green-warm-50', token: '--uswds-green-warm-50', value: { space: 'hex', value: '#6f7a41' } },
        { name: 'green-warm-60', token: '--uswds-green-warm-60', value: { space: 'hex', value: '#5a5f38' } },
        { name: 'green-warm-70', token: '--uswds-green-warm-70', value: { space: 'hex', value: '#45472f' } },
        { name: 'green-warm-80', token: '--uswds-green-warm-80', value: { space: 'hex', value: '#2d2f21' } },
        { name: 'green-warm-90', token: '--uswds-green-warm-90', value: { space: 'hex', value: '#171712' } },
        { name: 'green-warm-5v', token: '--uswds-green-warm-5v', value: { space: 'hex', value: '#f5fbc1' } },
        { name: 'green-warm-10v', token: '--uswds-green-warm-10v', value: { space: 'hex', value: '#e7f434' } },
        { name: 'green-warm-20v', token: '--uswds-green-warm-20v', value: { space: 'hex', value: '#c5d30a' } },
        { name: 'green-warm-30v', token: '--uswds-green-warm-30v', value: { space: 'hex', value: '#a3b72c' } },
        { name: 'green-warm-40v', token: '--uswds-green-warm-40v', value: { space: 'hex', value: '#7e9c1d' } },
        { name: 'green-warm-50v', token: '--uswds-green-warm-50v', value: { space: 'hex', value: '#6a7d00' } },
        { name: 'green-warm-60v', token: '--uswds-green-warm-60v', value: { space: 'hex', value: '#5a6613' } },
        { name: 'green-warm-70v', token: '--uswds-green-warm-70v', value: { space: 'hex', value: '#4b4e10' } },
        { name: 'green-warm-80v', token: '--uswds-green-warm-80v', value: { space: 'hex', value: '#38380b' } },
      ],
    },
    {
      name: 'Green',
      swatches: [
        { name: 'green-5', token: '--uswds-green-5', value: { space: 'hex', value: '#eaf4dd' } },
        { name: 'green-10', token: '--uswds-green-10', value: { space: 'hex', value: '#dfeacd' } },
        { name: 'green-20', token: '--uswds-green-20', value: { space: 'hex', value: '#b8d293' } },
        { name: 'green-30', token: '--uswds-green-30', value: { space: 'hex', value: '#9bb672' } },
        { name: 'green-40', token: '--uswds-green-40', value: { space: 'hex', value: '#7d9b4e' } },
        { name: 'green-50', token: '--uswds-green-50', value: { space: 'hex', value: '#607f35' } },
        { name: 'green-60', token: '--uswds-green-60', value: { space: 'hex', value: '#4c6424' } },
        { name: 'green-70', token: '--uswds-green-70', value: { space: 'hex', value: '#3c4a29' } },
        { name: 'green-80', token: '--uswds-green-80', value: { space: 'hex', value: '#293021' } },
        { name: 'green-90', token: '--uswds-green-90', value: { space: 'hex', value: '#161814' } },
        { name: 'green-5v', token: '--uswds-green-5v', value: { space: 'hex', value: '#ddf9c7' } },
        { name: 'green-10v', token: '--uswds-green-10v', value: { space: 'hex', value: '#c5ee93' } },
        { name: 'green-20v', token: '--uswds-green-20v', value: { space: 'hex', value: '#98d035' } },
        { name: 'green-30v', token: '--uswds-green-30v', value: { space: 'hex', value: '#7fb135' } },
        { name: 'green-40v', token: '--uswds-green-40v', value: { space: 'hex', value: '#719f2a' } },
        { name: 'green-50v', token: '--uswds-green-50v', value: { space: 'hex', value: '#538200' } },
        { name: 'green-60v', token: '--uswds-green-60v', value: { space: 'hex', value: '#466c04' } },
        { name: 'green-70v', token: '--uswds-green-70v', value: { space: 'hex', value: '#2f4a0b' } },
        { name: 'green-80v', token: '--uswds-green-80v', value: { space: 'hex', value: '#243413' } },
      ],
    },
    {
      name: 'Green Cool',
      swatches: [
        { name: 'green-cool-5', token: '--uswds-green-cool-5', value: { space: 'hex', value: '#ecf3ec' } },
        { name: 'green-cool-10', token: '--uswds-green-cool-10', value: { space: 'hex', value: '#dbebde' } },
        { name: 'green-cool-20', token: '--uswds-green-cool-20', value: { space: 'hex', value: '#b4d0b9' } },
        { name: 'green-cool-30', token: '--uswds-green-cool-30', value: { space: 'hex', value: '#86b98e' } },
        { name: 'green-cool-40', token: '--uswds-green-cool-40', value: { space: 'hex', value: '#5e9f69' } },
        { name: 'green-cool-50', token: '--uswds-green-cool-50', value: { space: 'hex', value: '#4d8055' } },
        { name: 'green-cool-60', token: '--uswds-green-cool-60', value: { space: 'hex', value: '#446443' } },
        { name: 'green-cool-70', token: '--uswds-green-cool-70', value: { space: 'hex', value: '#37493b' } },
        { name: 'green-cool-80', token: '--uswds-green-cool-80', value: { space: 'hex', value: '#28312a' } },
        { name: 'green-cool-90', token: '--uswds-green-cool-90', value: { space: 'hex', value: '#1a1f1a' } },
        { name: 'green-cool-5v', token: '--uswds-green-cool-5v', value: { space: 'hex', value: '#e3f5e1' } },
        { name: 'green-cool-10v', token: '--uswds-green-cool-10v', value: { space: 'hex', value: '#b7f5bd' } },
        { name: 'green-cool-20v', token: '--uswds-green-cool-20v', value: { space: 'hex', value: '#70e17b' } },
        { name: 'green-cool-30v', token: '--uswds-green-cool-30v', value: { space: 'hex', value: '#21c834' } },
        { name: 'green-cool-40v', token: '--uswds-green-cool-40v', value: { space: 'hex', value: '#00a91c' } },
        { name: 'green-cool-50v', token: '--uswds-green-cool-50v', value: { space: 'hex', value: '#008817' } },
        { name: 'green-cool-60v', token: '--uswds-green-cool-60v', value: { space: 'hex', value: '#216e1f' } },
        { name: 'green-cool-70v', token: '--uswds-green-cool-70v', value: { space: 'hex', value: '#154c21' } },
        { name: 'green-cool-80v', token: '--uswds-green-cool-80v', value: { space: 'hex', value: '#19311e' } },
      ],
    },
    {
      name: 'Mint',
      swatches: [
        { name: 'mint-5', token: '--uswds-mint-5', value: { space: 'hex', value: '#dbf6ed' } },
        { name: 'mint-10', token: '--uswds-mint-10', value: { space: 'hex', value: '#c7efe2' } },
        { name: 'mint-20', token: '--uswds-mint-20', value: { space: 'hex', value: '#92d9bb' } },
        { name: 'mint-30', token: '--uswds-mint-30', value: { space: 'hex', value: '#5abf95' } },
        { name: 'mint-40', token: '--uswds-mint-40', value: { space: 'hex', value: '#34a37e' } },
        { name: 'mint-50', token: '--uswds-mint-50', value: { space: 'hex', value: '#2e8367' } },
        { name: 'mint-60', token: '--uswds-mint-60', value: { space: 'hex', value: '#286846' } },
        { name: 'mint-70', token: '--uswds-mint-70', value: { space: 'hex', value: '#204e34' } },
        { name: 'mint-80', token: '--uswds-mint-80', value: { space: 'hex', value: '#193324' } },
        { name: 'mint-90', token: '--uswds-mint-90', value: { space: 'hex', value: '#0d1a12' } },
        { name: 'mint-5v', token: '--uswds-mint-5v', value: { space: 'hex', value: '#c9fbeb' } },
        { name: 'mint-10v', token: '--uswds-mint-10v', value: { space: 'hex', value: '#83fcd4' } },
        { name: 'mint-20v', token: '--uswds-mint-20v', value: { space: 'hex', value: '#0ceda6' } },
        { name: 'mint-30v', token: '--uswds-mint-30v', value: { space: 'hex', value: '#04c585' } },
        { name: 'mint-40v', token: '--uswds-mint-40v', value: { space: 'hex', value: '#00a871' } },
        { name: 'mint-50v', token: '--uswds-mint-50v', value: { space: 'hex', value: '#008659' } },
        { name: 'mint-60v', token: '--uswds-mint-60v', value: { space: 'hex', value: '#146947' } },
        { name: 'mint-70v', token: '--uswds-mint-70v', value: { space: 'hex', value: '#0c4e29' } },
        { name: 'mint-80v', token: '--uswds-mint-80v', value: { space: 'hex', value: '#0d351e' } },
      ],
    },
    {
      name: 'Mint Cool',
      swatches: [
        { name: 'mint-cool-5', token: '--uswds-mint-cool-5', value: { space: 'hex', value: '#e0f7f6' } },
        { name: 'mint-cool-10', token: '--uswds-mint-cool-10', value: { space: 'hex', value: '#c4eeeb' } },
        { name: 'mint-cool-20', token: '--uswds-mint-cool-20', value: { space: 'hex', value: '#9bd4cf' } },
        { name: 'mint-cool-30', token: '--uswds-mint-cool-30', value: { space: 'hex', value: '#6fbab3' } },
        { name: 'mint-cool-40', token: '--uswds-mint-cool-40', value: { space: 'hex', value: '#4f9e99' } },
        { name: 'mint-cool-50', token: '--uswds-mint-cool-50', value: { space: 'hex', value: '#40807e' } },
        { name: 'mint-cool-60', token: '--uswds-mint-cool-60', value: { space: 'hex', value: '#376462' } },
        { name: 'mint-cool-70', token: '--uswds-mint-cool-70', value: { space: 'hex', value: '#2a4b45' } },
        { name: 'mint-cool-80', token: '--uswds-mint-cool-80', value: { space: 'hex', value: '#203131' } },
        { name: 'mint-cool-90', token: '--uswds-mint-cool-90', value: { space: 'hex', value: '#111818' } },
        { name: 'mint-cool-5v', token: '--uswds-mint-cool-5v', value: { space: 'hex', value: '#d5fbf3' } },
        { name: 'mint-cool-10v', token: '--uswds-mint-cool-10v', value: { space: 'hex', value: '#7efbe1' } },
        { name: 'mint-cool-20v', token: '--uswds-mint-cool-20v', value: { space: 'hex', value: '#29e1cb' } },
        { name: 'mint-cool-30v', token: '--uswds-mint-cool-30v', value: { space: 'hex', value: '#1dc2ae' } },
        { name: 'mint-cool-40v', token: '--uswds-mint-cool-40v', value: { space: 'hex', value: '#00a398' } },
        { name: 'mint-cool-50v', token: '--uswds-mint-cool-50v', value: { space: 'hex', value: '#008480' } },
        { name: 'mint-cool-60v', token: '--uswds-mint-cool-60v', value: { space: 'hex', value: '#0f6460' } },
        { name: 'mint-cool-70v', token: '--uswds-mint-cool-70v', value: { space: 'hex', value: '#0b4b3f' } },
        { name: 'mint-cool-80v', token: '--uswds-mint-cool-80v', value: { space: 'hex', value: '#123131' } },
      ],
    },
    {
      name: 'Cyan',
      swatches: [
        { name: 'cyan-5', token: '--uswds-cyan-5', value: { space: 'hex', value: '#e7f6f8' } },
        { name: 'cyan-10', token: '--uswds-cyan-10', value: { space: 'hex', value: '#ccecf2' } },
        { name: 'cyan-20', token: '--uswds-cyan-20', value: { space: 'hex', value: '#99deea' } },
        { name: 'cyan-30', token: '--uswds-cyan-30', value: { space: 'hex', value: '#5dc0d1' } },
        { name: 'cyan-40', token: '--uswds-cyan-40', value: { space: 'hex', value: '#449dac' } },
        { name: 'cyan-50', token: '--uswds-cyan-50', value: { space: 'hex', value: '#168092' } },
        { name: 'cyan-60', token: '--uswds-cyan-60', value: { space: 'hex', value: '#2a646d' } },
        { name: 'cyan-70', token: '--uswds-cyan-70', value: { space: 'hex', value: '#2c4a4e' } },
        { name: 'cyan-80', token: '--uswds-cyan-80', value: { space: 'hex', value: '#203133' } },
        { name: 'cyan-90', token: '--uswds-cyan-90', value: { space: 'hex', value: '#111819' } },
        { name: 'cyan-5v', token: '--uswds-cyan-5v', value: { space: 'hex', value: '#e5faff' } },
        { name: 'cyan-10v', token: '--uswds-cyan-10v', value: { space: 'hex', value: '#a8f2ff' } },
        { name: 'cyan-20v', token: '--uswds-cyan-20v', value: { space: 'hex', value: '#52daf2' } },
        { name: 'cyan-30v', token: '--uswds-cyan-30v', value: { space: 'hex', value: '#00bde3' } },
        { name: 'cyan-40v', token: '--uswds-cyan-40v', value: { space: 'hex', value: '#009ec1' } },
        { name: 'cyan-50v', token: '--uswds-cyan-50v', value: { space: 'hex', value: '#0081a1' } },
        { name: 'cyan-60v', token: '--uswds-cyan-60v', value: { space: 'hex', value: '#00687d' } },
        { name: 'cyan-70v', token: '--uswds-cyan-70v', value: { space: 'hex', value: '#0e4f5c' } },
        { name: 'cyan-80v', token: '--uswds-cyan-80v', value: { space: 'hex', value: '#093b44' } },
      ],
    },
    {
      name: 'Blue Cool',
      swatches: [
        { name: 'blue-cool-5', token: '--uswds-blue-cool-5', value: { space: 'hex', value: '#e7f2f5' } },
        { name: 'blue-cool-10', token: '--uswds-blue-cool-10', value: { space: 'hex', value: '#dae9ee' } },
        { name: 'blue-cool-20', token: '--uswds-blue-cool-20', value: { space: 'hex', value: '#adcfdc' } },
        { name: 'blue-cool-30', token: '--uswds-blue-cool-30', value: { space: 'hex', value: '#82b4c9' } },
        { name: 'blue-cool-40', token: '--uswds-blue-cool-40', value: { space: 'hex', value: '#6499af' } },
        { name: 'blue-cool-50', token: '--uswds-blue-cool-50', value: { space: 'hex', value: '#3a7d95' } },
        { name: 'blue-cool-60', token: '--uswds-blue-cool-60', value: { space: 'hex', value: '#2e6276' } },
        { name: 'blue-cool-70', token: '--uswds-blue-cool-70', value: { space: 'hex', value: '#224a58' } },
        { name: 'blue-cool-80', token: '--uswds-blue-cool-80', value: { space: 'hex', value: '#14333d' } },
        { name: 'blue-cool-90', token: '--uswds-blue-cool-90', value: { space: 'hex', value: '#0f191c' } },
        { name: 'blue-cool-5v', token: '--uswds-blue-cool-5v', value: { space: 'hex', value: '#e1f3f8' } },
        { name: 'blue-cool-10v', token: '--uswds-blue-cool-10v', value: { space: 'hex', value: '#c3ebfa' } },
        { name: 'blue-cool-20v', token: '--uswds-blue-cool-20v', value: { space: 'hex', value: '#97d4ea' } },
        { name: 'blue-cool-30v', token: '--uswds-blue-cool-30v', value: { space: 'hex', value: '#59b9de' } },
        { name: 'blue-cool-40v', token: '--uswds-blue-cool-40v', value: { space: 'hex', value: '#28a0cb' } },
        { name: 'blue-cool-50v', token: '--uswds-blue-cool-50v', value: { space: 'hex', value: '#0d7ea2' } },
        { name: 'blue-cool-60v', token: '--uswds-blue-cool-60v', value: { space: 'hex', value: '#07648d' } },
        { name: 'blue-cool-70v', token: '--uswds-blue-cool-70v', value: { space: 'hex', value: '#074b69' } },
        { name: 'blue-cool-80v', token: '--uswds-blue-cool-80v', value: { space: 'hex', value: '#002d3f' } },
      ],
    },
    {
      name: 'Blue',
      swatches: [
        { name: 'blue-5', token: '--uswds-blue-5', value: { space: 'hex', value: '#eff6fb' } },
        { name: 'blue-10', token: '--uswds-blue-10', value: { space: 'hex', value: '#d9e8f6' } },
        { name: 'blue-20', token: '--uswds-blue-20', value: { space: 'hex', value: '#aacdec' } },
        { name: 'blue-30', token: '--uswds-blue-30', value: { space: 'hex', value: '#73b3e7' } },
        { name: 'blue-40', token: '--uswds-blue-40', value: { space: 'hex', value: '#4f97d1' } },
        { name: 'blue-50', token: '--uswds-blue-50', value: { space: 'hex', value: '#2378c3' } },
        { name: 'blue-60', token: '--uswds-blue-60', value: { space: 'hex', value: '#2c608a' } },
        { name: 'blue-70', token: '--uswds-blue-70', value: { space: 'hex', value: '#274863' } },
        { name: 'blue-80', token: '--uswds-blue-80', value: { space: 'hex', value: '#1f303e' } },
        { name: 'blue-90', token: '--uswds-blue-90', value: { space: 'hex', value: '#11181d' } },
        { name: 'blue-5v', token: '--uswds-blue-5v', value: { space: 'hex', value: '#e8f5ff' } },
        { name: 'blue-10v', token: '--uswds-blue-10v', value: { space: 'hex', value: '#cfe8ff' } },
        { name: 'blue-20v', token: '--uswds-blue-20v', value: { space: 'hex', value: '#a1d3ff' } },
        { name: 'blue-30v', token: '--uswds-blue-30v', value: { space: 'hex', value: '#58b4ff' } },
        { name: 'blue-40v', token: '--uswds-blue-40v', value: { space: 'hex', value: '#2491ff' } },
        { name: 'blue-50v', token: '--uswds-blue-50v', value: { space: 'hex', value: '#0076d6' } },
        { name: 'blue-60v', token: '--uswds-blue-60v', value: { space: 'hex', value: '#005ea2' } },
        { name: 'blue-70v', token: '--uswds-blue-70v', value: { space: 'hex', value: '#0b4778' } },
        { name: 'blue-80v', token: '--uswds-blue-80v', value: { space: 'hex', value: '#112f4e' } },
      ],
    },
    {
      name: 'Blue Warm',
      swatches: [
        { name: 'blue-warm-5', token: '--uswds-blue-warm-5', value: { space: 'hex', value: '#ecf1f7' } },
        { name: 'blue-warm-10', token: '--uswds-blue-warm-10', value: { space: 'hex', value: '#e1e7f1' } },
        { name: 'blue-warm-20', token: '--uswds-blue-warm-20', value: { space: 'hex', value: '#bbcae4' } },
        { name: 'blue-warm-30', token: '--uswds-blue-warm-30', value: { space: 'hex', value: '#98afd2' } },
        { name: 'blue-warm-40', token: '--uswds-blue-warm-40', value: { space: 'hex', value: '#7292c7' } },
        { name: 'blue-warm-50', token: '--uswds-blue-warm-50', value: { space: 'hex', value: '#4a77b4' } },
        { name: 'blue-warm-60', token: '--uswds-blue-warm-60', value: { space: 'hex', value: '#345d96' } },
        { name: 'blue-warm-70', token: '--uswds-blue-warm-70', value: { space: 'hex', value: '#2f4668' } },
        { name: 'blue-warm-80', token: '--uswds-blue-warm-80', value: { space: 'hex', value: '#252f3e' } },
        { name: 'blue-warm-90', token: '--uswds-blue-warm-90', value: { space: 'hex', value: '#13171f' } },
        { name: 'blue-warm-5v', token: '--uswds-blue-warm-5v', value: { space: 'hex', value: '#edf5ff' } },
        { name: 'blue-warm-10v', token: '--uswds-blue-warm-10v', value: { space: 'hex', value: '#d4e5ff' } },
        { name: 'blue-warm-20v', token: '--uswds-blue-warm-20v', value: { space: 'hex', value: '#adcdff' } },
        { name: 'blue-warm-30v', token: '--uswds-blue-warm-30v', value: { space: 'hex', value: '#81aefc' } },
        { name: 'blue-warm-40v', token: '--uswds-blue-warm-40v', value: { space: 'hex', value: '#5994f6' } },
        { name: 'blue-warm-50v', token: '--uswds-blue-warm-50v', value: { space: 'hex', value: '#2672de' } },
        { name: 'blue-warm-60v', token: '--uswds-blue-warm-60v', value: { space: 'hex', value: '#0050d8' } },
        { name: 'blue-warm-70v', token: '--uswds-blue-warm-70v', value: { space: 'hex', value: '#1a4480' } },
        { name: 'blue-warm-80v', token: '--uswds-blue-warm-80v', value: { space: 'hex', value: '#162e51' } },
      ],
    },
    {
      name: 'Indigo Cool',
      swatches: [
        { name: 'indigo-cool-5', token: '--uswds-indigo-cool-5', value: { space: 'hex', value: '#eef0f9' } },
        { name: 'indigo-cool-10', token: '--uswds-indigo-cool-10', value: { space: 'hex', value: '#e1e6f9' } },
        { name: 'indigo-cool-20', token: '--uswds-indigo-cool-20', value: { space: 'hex', value: '#bbc8f5' } },
        { name: 'indigo-cool-30', token: '--uswds-indigo-cool-30', value: { space: 'hex', value: '#96abee' } },
        { name: 'indigo-cool-40', token: '--uswds-indigo-cool-40', value: { space: 'hex', value: '#6b8ee8' } },
        { name: 'indigo-cool-50', token: '--uswds-indigo-cool-50', value: { space: 'hex', value: '#496fd8' } },
        { name: 'indigo-cool-60', token: '--uswds-indigo-cool-60', value: { space: 'hex', value: '#3f57a6' } },
        { name: 'indigo-cool-70', token: '--uswds-indigo-cool-70', value: { space: 'hex', value: '#374274' } },
        { name: 'indigo-cool-80', token: '--uswds-indigo-cool-80', value: { space: 'hex', value: '#292d42' } },
        { name: 'indigo-cool-90', token: '--uswds-indigo-cool-90', value: { space: 'hex', value: '#151622' } },
        { name: 'indigo-cool-5v', token: '--uswds-indigo-cool-5v', value: { space: 'hex', value: '#edf0ff' } },
        { name: 'indigo-cool-10v', token: '--uswds-indigo-cool-10v', value: { space: 'hex', value: '#dee5ff' } },
        { name: 'indigo-cool-20v', token: '--uswds-indigo-cool-20v', value: { space: 'hex', value: '#b8c8ff' } },
        { name: 'indigo-cool-30v', token: '--uswds-indigo-cool-30v', value: { space: 'hex', value: '#94adff' } },
        { name: 'indigo-cool-40v', token: '--uswds-indigo-cool-40v', value: { space: 'hex', value: '#628ef4' } },
        { name: 'indigo-cool-50v', token: '--uswds-indigo-cool-50v', value: { space: 'hex', value: '#4866ff' } },
        { name: 'indigo-cool-60v', token: '--uswds-indigo-cool-60v', value: { space: 'hex', value: '#3e4ded' } },
        { name: 'indigo-cool-70v', token: '--uswds-indigo-cool-70v', value: { space: 'hex', value: '#222fbf' } },
        { name: 'indigo-cool-80v', token: '--uswds-indigo-cool-80v', value: { space: 'hex', value: '#1b2b85' } },
      ],
    },
    {
      name: 'Indigo',
      swatches: [
        { name: 'indigo-5', token: '--uswds-indigo-5', value: { space: 'hex', value: '#efeff8' } },
        { name: 'indigo-10', token: '--uswds-indigo-10', value: { space: 'hex', value: '#e5e4fa' } },
        { name: 'indigo-20', token: '--uswds-indigo-20', value: { space: 'hex', value: '#c5c5f3' } },
        { name: 'indigo-30', token: '--uswds-indigo-30', value: { space: 'hex', value: '#a5a8eb' } },
        { name: 'indigo-40', token: '--uswds-indigo-40', value: { space: 'hex', value: '#8889db' } },
        { name: 'indigo-50', token: '--uswds-indigo-50', value: { space: 'hex', value: '#676cc8' } },
        { name: 'indigo-60', token: '--uswds-indigo-60', value: { space: 'hex', value: '#4d52af' } },
        { name: 'indigo-70', token: '--uswds-indigo-70', value: { space: 'hex', value: '#3d4076' } },
        { name: 'indigo-80', token: '--uswds-indigo-80', value: { space: 'hex', value: '#2b2c40' } },
        { name: 'indigo-90', token: '--uswds-indigo-90', value: { space: 'hex', value: '#16171f' } },
        { name: 'indigo-5v', token: '--uswds-indigo-5v', value: { space: 'hex', value: '#f0f0ff' } },
        { name: 'indigo-10v', token: '--uswds-indigo-10v', value: { space: 'hex', value: '#e0e0ff' } },
        { name: 'indigo-20v', token: '--uswds-indigo-20v', value: { space: 'hex', value: '#ccceff' } },
        { name: 'indigo-30v', token: '--uswds-indigo-30v', value: { space: 'hex', value: '#a3a7fa' } },
        { name: 'indigo-40v', token: '--uswds-indigo-40v', value: { space: 'hex', value: '#8289ff' } },
        { name: 'indigo-50v', token: '--uswds-indigo-50v', value: { space: 'hex', value: '#656bd7' } },
        { name: 'indigo-60v', token: '--uswds-indigo-60v', value: { space: 'hex', value: '#4a50c4' } },
        { name: 'indigo-70v', token: '--uswds-indigo-70v', value: { space: 'hex', value: '#3333a3' } },
        { name: 'indigo-80v', token: '--uswds-indigo-80v', value: { space: 'hex', value: '#212463' } },
      ],
    },
    {
      name: 'Indigo Warm',
      swatches: [
        { name: 'indigo-warm-5', token: '--uswds-indigo-warm-5', value: { space: 'hex', value: '#f1eff7' } },
        { name: 'indigo-warm-10', token: '--uswds-indigo-warm-10', value: { space: 'hex', value: '#e7e3fa' } },
        { name: 'indigo-warm-20', token: '--uswds-indigo-warm-20', value: { space: 'hex', value: '#cbc4f2' } },
        { name: 'indigo-warm-30', token: '--uswds-indigo-warm-30', value: { space: 'hex', value: '#afa5e8' } },
        { name: 'indigo-warm-40', token: '--uswds-indigo-warm-40', value: { space: 'hex', value: '#9287d8' } },
        { name: 'indigo-warm-50', token: '--uswds-indigo-warm-50', value: { space: 'hex', value: '#7665d1' } },
        { name: 'indigo-warm-60', token: '--uswds-indigo-warm-60', value: { space: 'hex', value: '#5e519e' } },
        { name: 'indigo-warm-70', token: '--uswds-indigo-warm-70', value: { space: 'hex', value: '#453c7b' } },
        { name: 'indigo-warm-80', token: '--uswds-indigo-warm-80', value: { space: 'hex', value: '#2e2c40' } },
        { name: 'indigo-warm-90', token: '--uswds-indigo-warm-90', value: { space: 'hex', value: '#18161d' } },
        { name: 'indigo-warm-5v', token: '--uswds-indigo-warm-5v', value: { space: 'hex', value: '#f5f2ff' } },
        { name: 'indigo-warm-10v', token: '--uswds-indigo-warm-10v', value: { space: 'hex', value: '#e4deff' } },
        { name: 'indigo-warm-20v', token: '--uswds-indigo-warm-20v', value: { space: 'hex', value: '#cfc4fd' } },
        { name: 'indigo-warm-30v', token: '--uswds-indigo-warm-30v', value: { space: 'hex', value: '#b69fff' } },
        { name: 'indigo-warm-40v', token: '--uswds-indigo-warm-40v', value: { space: 'hex', value: '#967efb' } },
        { name: 'indigo-warm-50v', token: '--uswds-indigo-warm-50v', value: { space: 'hex', value: '#745fe9' } },
        { name: 'indigo-warm-60v', token: '--uswds-indigo-warm-60v', value: { space: 'hex', value: '#5942d2' } },
        { name: 'indigo-warm-70v', token: '--uswds-indigo-warm-70v', value: { space: 'hex', value: '#3d2c9d' } },
        { name: 'indigo-warm-80v', token: '--uswds-indigo-warm-80v', value: { space: 'hex', value: '#261f5b' } },
      ],
    },
    {
      name: 'Violet',
      swatches: [
        { name: 'violet-5', token: '--uswds-violet-5', value: { space: 'hex', value: '#f4f1f9' } },
        { name: 'violet-10', token: '--uswds-violet-10', value: { space: 'hex', value: '#ebe3f9' } },
        { name: 'violet-20', token: '--uswds-violet-20', value: { space: 'hex', value: '#d0c3e9' } },
        { name: 'violet-30', token: '--uswds-violet-30', value: { space: 'hex', value: '#b8a2e3' } },
        { name: 'violet-40', token: '--uswds-violet-40', value: { space: 'hex', value: '#9d84d2' } },
        { name: 'violet-50', token: '--uswds-violet-50', value: { space: 'hex', value: '#8168b3' } },
        { name: 'violet-60', token: '--uswds-violet-60', value: { space: 'hex', value: '#665190' } },
        { name: 'violet-70', token: '--uswds-violet-70', value: { space: 'hex', value: '#4c3d69' } },
        { name: 'violet-80', token: '--uswds-violet-80', value: { space: 'hex', value: '#312b3f' } },
        { name: 'violet-90', token: '--uswds-violet-90', value: { space: 'hex', value: '#18161d' } },
        { name: 'violet-5v', token: '--uswds-violet-5v', value: { space: 'hex', value: '#f7f2ff' } },
        { name: 'violet-10v', token: '--uswds-violet-10v', value: { space: 'hex', value: '#ede3ff' } },
        { name: 'violet-20v', token: '--uswds-violet-20v', value: { space: 'hex', value: '#d5bfff' } },
        { name: 'violet-30v', token: '--uswds-violet-30v', value: { space: 'hex', value: '#c39deb' } },
        { name: 'violet-40v', token: '--uswds-violet-40v', value: { space: 'hex', value: '#ad79e9' } },
        { name: 'violet-50v', token: '--uswds-violet-50v', value: { space: 'hex', value: '#9355dc' } },
        { name: 'violet-60v', token: '--uswds-violet-60v', value: { space: 'hex', value: '#783cb9' } },
        { name: 'violet-70v', token: '--uswds-violet-70v', value: { space: 'hex', value: '#54278f' } },
        { name: 'violet-80v', token: '--uswds-violet-80v', value: { space: 'hex', value: '#39215e' } },
      ],
    },
    {
      name: 'Violet Warm',
      swatches: [
        { name: 'violet-warm-5', token: '--uswds-violet-warm-5', value: { space: 'hex', value: '#f8f0f9' } },
        { name: 'violet-warm-10', token: '--uswds-violet-warm-10', value: { space: 'hex', value: '#f6dff8' } },
        { name: 'violet-warm-20', token: '--uswds-violet-warm-20', value: { space: 'hex', value: '#e2bee4' } },
        { name: 'violet-warm-30', token: '--uswds-violet-warm-30', value: { space: 'hex', value: '#d29ad8' } },
        { name: 'violet-warm-40', token: '--uswds-violet-warm-40', value: { space: 'hex', value: '#bf77c8' } },
        { name: 'violet-warm-50', token: '--uswds-violet-warm-50', value: { space: 'hex', value: '#b04abd' } },
        { name: 'violet-warm-60', token: '--uswds-violet-warm-60', value: { space: 'hex', value: '#864381' } },
        { name: 'violet-warm-70', token: '--uswds-violet-warm-70', value: { space: 'hex', value: '#5c395a' } },
        { name: 'violet-warm-80', token: '--uswds-violet-warm-80', value: { space: 'hex', value: '#382936' } },
        { name: 'violet-warm-90', token: '--uswds-violet-warm-90', value: { space: 'hex', value: '#1b151b' } },
        { name: 'violet-warm-5v', token: '--uswds-violet-warm-5v', value: { space: 'hex', value: '#fef2ff' } },
        { name: 'violet-warm-10v', token: '--uswds-violet-warm-10v', value: { space: 'hex', value: '#fbdcff' } },
        { name: 'violet-warm-20v', token: '--uswds-violet-warm-20v', value: { space: 'hex', value: '#f4b2ff' } },
        { name: 'violet-warm-30v', token: '--uswds-violet-warm-30v', value: { space: 'hex', value: '#ee83ff' } },
        { name: 'violet-warm-40v', token: '--uswds-violet-warm-40v', value: { space: 'hex', value: '#d85bef' } },
        { name: 'violet-warm-50v', token: '--uswds-violet-warm-50v', value: { space: 'hex', value: '#be32d0' } },
        { name: 'violet-warm-60v', token: '--uswds-violet-warm-60v', value: { space: 'hex', value: '#93348c' } },
        { name: 'violet-warm-70v', token: '--uswds-violet-warm-70v', value: { space: 'hex', value: '#711e6c' } },
        { name: 'violet-warm-80v', token: '--uswds-violet-warm-80v', value: { space: 'hex', value: '#481441' } },
      ],
    },
    {
      name: 'Magenta',
      swatches: [
        { name: 'magenta-5', token: '--uswds-magenta-5', value: { space: 'hex', value: '#f9f0f2' } },
        { name: 'magenta-10', token: '--uswds-magenta-10', value: { space: 'hex', value: '#f6e1e8' } },
        { name: 'magenta-20', token: '--uswds-magenta-20', value: { space: 'hex', value: '#f0bbcc' } },
        { name: 'magenta-30', token: '--uswds-magenta-30', value: { space: 'hex', value: '#e895b3' } },
        { name: 'magenta-40', token: '--uswds-magenta-40', value: { space: 'hex', value: '#e0699f' } },
        { name: 'magenta-50', token: '--uswds-magenta-50', value: { space: 'hex', value: '#c84281' } },
        { name: 'magenta-60', token: '--uswds-magenta-60', value: { space: 'hex', value: '#8b4566' } },
        { name: 'magenta-70', token: '--uswds-magenta-70', value: { space: 'hex', value: '#66364b' } },
        { name: 'magenta-80', token: '--uswds-magenta-80', value: { space: 'hex', value: '#402731' } },
        { name: 'magenta-90', token: '--uswds-magenta-90', value: { space: 'hex', value: '#1b1617' } },
        { name: 'magenta-5v', token: '--uswds-magenta-5v', value: { space: 'hex', value: '#fff2f5' } },
        { name: 'magenta-10v', token: '--uswds-magenta-10v', value: { space: 'hex', value: '#ffddea' } },
        { name: 'magenta-20v', token: '--uswds-magenta-20v', value: { space: 'hex', value: '#ffb4cf' } },
        { name: 'magenta-30v', token: '--uswds-magenta-30v', value: { space: 'hex', value: '#ff87b2' } },
        { name: 'magenta-40v', token: '--uswds-magenta-40v', value: { space: 'hex', value: '#fd4496' } },
        { name: 'magenta-50v', token: '--uswds-magenta-50v', value: { space: 'hex', value: '#d72d79' } },
        { name: 'magenta-60v', token: '--uswds-magenta-60v', value: { space: 'hex', value: '#ab2165' } },
        { name: 'magenta-70v', token: '--uswds-magenta-70v', value: { space: 'hex', value: '#731f44' } },
        { name: 'magenta-80v', token: '--uswds-magenta-80v', value: { space: 'hex', value: '#4f172e' } },
      ],
    },
    {
      name: 'Gray Cool',
      swatches: [
        { name: 'gray-cool-1', token: '--uswds-gray-cool-1', value: { space: 'hex', value: '#fbfcfd' } },
        { name: 'gray-cool-2', token: '--uswds-gray-cool-2', value: { space: 'hex', value: '#f7f9fa' } },
        { name: 'gray-cool-3', token: '--uswds-gray-cool-3', value: { space: 'hex', value: '#f5f6f7' } },
        { name: 'gray-cool-4', token: '--uswds-gray-cool-4', value: { space: 'hex', value: '#f1f3f6' } },
        { name: 'gray-cool-5', token: '--uswds-gray-cool-5', value: { space: 'hex', value: '#edeff0' } },
        { name: 'gray-cool-10', token: '--uswds-gray-cool-10', value: { space: 'hex', value: '#dfe1e2' } },
        { name: 'gray-cool-20', token: '--uswds-gray-cool-20', value: { space: 'hex', value: '#c6cace' } },
        { name: 'gray-cool-30', token: '--uswds-gray-cool-30', value: { space: 'hex', value: '#a9aeb1' } },
        { name: 'gray-cool-40', token: '--uswds-gray-cool-40', value: { space: 'hex', value: '#8d9297' } },
        { name: 'gray-cool-50', token: '--uswds-gray-cool-50', value: { space: 'hex', value: '#71767a' } },
        { name: 'gray-cool-60', token: '--uswds-gray-cool-60', value: { space: 'hex', value: '#565c65' } },
        { name: 'gray-cool-70', token: '--uswds-gray-cool-70', value: { space: 'hex', value: '#3d4551' } },
        { name: 'gray-cool-80', token: '--uswds-gray-cool-80', value: { space: 'hex', value: '#2d2e2f' } },
        { name: 'gray-cool-90', token: '--uswds-gray-cool-90', value: { space: 'hex', value: '#1c1d1f' } },
      ],
    },
    {
      name: 'Gray',
      swatches: [
        { name: 'gray-1', token: '--uswds-gray-1', value: { space: 'hex', value: '#fcfcfc' } },
        { name: 'gray-2', token: '--uswds-gray-2', value: { space: 'hex', value: '#f9f9f9' } },
        { name: 'gray-3', token: '--uswds-gray-3', value: { space: 'hex', value: '#f6f6f6' } },
        { name: 'gray-4', token: '--uswds-gray-4', value: { space: 'hex', value: '#f3f3f3' } },
        { name: 'gray-5', token: '--uswds-gray-5', value: { space: 'hex', value: '#f0f0f0' } },
        { name: 'gray-10', token: '--uswds-gray-10', value: { space: 'hex', value: '#e6e6e6' } },
        { name: 'gray-20', token: '--uswds-gray-20', value: { space: 'hex', value: '#c9c9c9' } },
        { name: 'gray-30', token: '--uswds-gray-30', value: { space: 'hex', value: '#adadad' } },
        { name: 'gray-40', token: '--uswds-gray-40', value: { space: 'hex', value: '#919191' } },
        { name: 'gray-50', token: '--uswds-gray-50', value: { space: 'hex', value: '#757575' } },
        { name: 'gray-60', token: '--uswds-gray-60', value: { space: 'hex', value: '#5c5c5c' } },
        { name: 'gray-70', token: '--uswds-gray-70', value: { space: 'hex', value: '#454545' } },
        { name: 'gray-80', token: '--uswds-gray-80', value: { space: 'hex', value: '#2e2e2e' } },
        { name: 'gray-90', token: '--uswds-gray-90', value: { space: 'hex', value: '#1b1b1b' } },
        { name: 'gray-100', token: '--uswds-gray-100', value: { space: 'hex', value: '#000000' } },
      ],
    },
    {
      name: 'Gray Warm',
      swatches: [
        { name: 'gray-warm-1', token: '--uswds-gray-warm-1', value: { space: 'hex', value: '#fcfcfb' } },
        { name: 'gray-warm-2', token: '--uswds-gray-warm-2', value: { space: 'hex', value: '#f9f9f7' } },
        { name: 'gray-warm-3', token: '--uswds-gray-warm-3', value: { space: 'hex', value: '#f6f6f2' } },
        { name: 'gray-warm-4', token: '--uswds-gray-warm-4', value: { space: 'hex', value: '#f5f5f0' } },
        { name: 'gray-warm-5', token: '--uswds-gray-warm-5', value: { space: 'hex', value: '#f0f0ec' } },
        { name: 'gray-warm-10', token: '--uswds-gray-warm-10', value: { space: 'hex', value: '#e6e6e2' } },
        { name: 'gray-warm-20', token: '--uswds-gray-warm-20', value: { space: 'hex', value: '#cac9c0' } },
        { name: 'gray-warm-30', token: '--uswds-gray-warm-30', value: { space: 'hex', value: '#afaea2' } },
        { name: 'gray-warm-40', token: '--uswds-gray-warm-40', value: { space: 'hex', value: '#929285' } },
        { name: 'gray-warm-50', token: '--uswds-gray-warm-50', value: { space: 'hex', value: '#76766a' } },
        { name: 'gray-warm-60', token: '--uswds-gray-warm-60', value: { space: 'hex', value: '#5d5d52' } },
        { name: 'gray-warm-70', token: '--uswds-gray-warm-70', value: { space: 'hex', value: '#454540' } },
        { name: 'gray-warm-80', token: '--uswds-gray-warm-80', value: { space: 'hex', value: '#2e2e2a' } },
        { name: 'gray-warm-90', token: '--uswds-gray-warm-90', value: { space: 'hex', value: '#171716' } },
      ],
    },
    {
      name: 'Black Transparent',
      swatches: [
        {
          name: 'black-transparent-5',
          token: '--uswds-black-transparent-5',
          value: { space: 'hex', value: '#00000003' },
        },
        {
          name: 'black-transparent-10',
          token: '--uswds-black-transparent-10',
          value: { space: 'hex', value: '#0000001a' },
        },
        {
          name: 'black-transparent-20',
          token: '--uswds-black-transparent-20',
          value: { space: 'hex', value: '#00000033' },
        },
        {
          name: 'black-transparent-30',
          token: '--uswds-black-transparent-30',
          value: { space: 'hex', value: '#0000004d' },
        },
        {
          name: 'black-transparent-40',
          token: '--uswds-black-transparent-40',
          value: { space: 'hex', value: '#00000066' },
        },
        {
          name: 'black-transparent-50',
          token: '--uswds-black-transparent-50',
          value: { space: 'hex', value: '#00000080' },
        },
        {
          name: 'black-transparent-60',
          token: '--uswds-black-transparent-60',
          value: { space: 'hex', value: '#00000099' },
        },
        {
          name: 'black-transparent-70',
          token: '--uswds-black-transparent-70',
          value: { space: 'hex', value: '#000000b3' },
        },
        {
          name: 'black-transparent-80',
          token: '--uswds-black-transparent-80',
          value: { space: 'hex', value: '#000000cc' },
        },
        {
          name: 'black-transparent-90',
          token: '--uswds-black-transparent-90',
          value: { space: 'hex', value: '#000000e6' },
        },
      ],
    },
    {
      name: 'White Transparent',
      swatches: [
        {
          name: 'white-transparent-5',
          token: '--uswds-white-transparent-5',
          value: { space: 'hex', value: '#ffffff03' },
        },
        {
          name: 'white-transparent-10',
          token: '--uswds-white-transparent-10',
          value: { space: 'hex', value: '#ffffff1a' },
        },
        {
          name: 'white-transparent-20',
          token: '--uswds-white-transparent-20',
          value: { space: 'hex', value: '#ffffff33' },
        },
        {
          name: 'white-transparent-30',
          token: '--uswds-white-transparent-30',
          value: { space: 'hex', value: '#ffffff4d' },
        },
        {
          name: 'white-transparent-40',
          token: '--uswds-white-transparent-40',
          value: { space: 'hex', value: '#ffffff66' },
        },
        {
          name: 'white-transparent-50',
          token: '--uswds-white-transparent-50',
          value: { space: 'hex', value: '#ffffff80' },
        },
        {
          name: 'white-transparent-60',
          token: '--uswds-white-transparent-60',
          value: { space: 'hex', value: '#ffffff99' },
        },
        {
          name: 'white-transparent-70',
          token: '--uswds-white-transparent-70',
          value: { space: 'hex', value: '#ffffffb3' },
        },
        {
          name: 'white-transparent-80',
          token: '--uswds-white-transparent-80',
          value: { space: 'hex', value: '#ffffffcc' },
        },
        {
          name: 'white-transparent-90',
          token: '--uswds-white-transparent-90',
          value: { space: 'hex', value: '#ffffffe6' },
        },
      ],
    },
  ],
} satisfies Palette
