import type { Palette } from './types'

const sourceUrl = 'https://webawesome.com/docs/color-palettes'

/** WebAwesome colors normalized from upstream design tokens. */
export const webawesomePalette = {
  id: 'webawesome',
  name: 'WebAwesome',
  sourceUrl: sourceUrl,
  groups: [
    {
      name: 'Red',
      swatches: [
        { name: 'red-95', token: '--wa-color-red-95', value: { space: 'hex', value: '#fff0ef' } },
        { name: 'red-90', token: '--wa-color-red-90', value: { space: 'hex', value: '#ffdedc' } },
        { name: 'red-80', token: '--wa-color-red-80', value: { space: 'hex', value: '#ffb8b6' } },
        { name: 'red-70', token: '--wa-color-red-70', value: { space: 'hex', value: '#fd8f90' } },
        { name: 'red-60', token: '--wa-color-red-60', value: { space: 'hex', value: '#f3676c' } },
        { name: 'red-50', token: '--wa-color-red-50', value: { space: 'hex', value: '#dc3146' } },
        { name: 'red-40', token: '--wa-color-red-40', value: { space: 'hex', value: '#b30532' } },
        { name: 'red-30', token: '--wa-color-red-30', value: { space: 'hex', value: '#8a132c' } },
        { name: 'red-20', token: '--wa-color-red-20', value: { space: 'hex', value: '#631323' } },
        { name: 'red-10', token: '--wa-color-red-10', value: { space: 'hex', value: '#3e0913' } },
        { name: 'red-05', token: '--wa-color-red-05', value: { space: 'hex', value: '#2a040b' } },
      ],
    },
    {
      name: 'Orange',
      swatches: [
        { name: 'orange-95', token: '--wa-color-orange-95', value: { space: 'hex', value: '#fff0e6' } },
        { name: 'orange-90', token: '--wa-color-orange-90', value: { space: 'hex', value: '#ffdfca' } },
        { name: 'orange-80', token: '--wa-color-orange-80', value: { space: 'hex', value: '#ffbb94' } },
        { name: 'orange-70', token: '--wa-color-orange-70', value: { space: 'hex', value: '#ff9266' } },
        { name: 'orange-60', token: '--wa-color-orange-60', value: { space: 'hex', value: '#f46a45' } },
        { name: 'orange-50', token: '--wa-color-orange-50', value: { space: 'hex', value: '#cd491c' } },
        { name: 'orange-40', token: '--wa-color-orange-40', value: { space: 'hex', value: '#9f3501' } },
        { name: 'orange-30', token: '--wa-color-orange-30', value: { space: 'hex', value: '#802700' } },
        { name: 'orange-20', token: '--wa-color-orange-20', value: { space: 'hex', value: '#601b00' } },
        { name: 'orange-10', token: '--wa-color-orange-10', value: { space: 'hex', value: '#3c0d00' } },
        { name: 'orange-05', token: '--wa-color-orange-05', value: { space: 'hex', value: '#280600' } },
      ],
    },
    {
      name: 'Yellow',
      swatches: [
        { name: 'yellow-95', token: '--wa-color-yellow-95', value: { space: 'hex', value: '#fef3cd' } },
        { name: 'yellow-90', token: '--wa-color-yellow-90', value: { space: 'hex', value: '#ffe495' } },
        { name: 'yellow-80', token: '--wa-color-yellow-80', value: { space: 'hex', value: '#fac22b' } },
        { name: 'yellow-70', token: '--wa-color-yellow-70', value: { space: 'hex', value: '#ef9d00' } },
        { name: 'yellow-60', token: '--wa-color-yellow-60', value: { space: 'hex', value: '#da7e00' } },
        { name: 'yellow-50', token: '--wa-color-yellow-50', value: { space: 'hex', value: '#b45f04' } },
        { name: 'yellow-40', token: '--wa-color-yellow-40', value: { space: 'hex', value: '#8c4602' } },
        { name: 'yellow-30', token: '--wa-color-yellow-30', value: { space: 'hex', value: '#6f3601' } },
        { name: 'yellow-20', token: '--wa-color-yellow-20', value: { space: 'hex', value: '#532600' } },
        { name: 'yellow-10', token: '--wa-color-yellow-10', value: { space: 'hex', value: '#331600' } },
        { name: 'yellow-05', token: '--wa-color-yellow-05', value: { space: 'hex', value: '#220c00' } },
      ],
    },
    {
      name: 'Green',
      swatches: [
        { name: 'green-95', token: '--wa-color-green-95', value: { space: 'hex', value: '#e3f9e3' } },
        { name: 'green-90', token: '--wa-color-green-90', value: { space: 'hex', value: '#c2f2c1' } },
        { name: 'green-80', token: '--wa-color-green-80', value: { space: 'hex', value: '#93da98' } },
        { name: 'green-70', token: '--wa-color-green-70', value: { space: 'hex', value: '#5dc36f' } },
        { name: 'green-60', token: '--wa-color-green-60', value: { space: 'hex', value: '#00ac49' } },
        { name: 'green-50', token: '--wa-color-green-50', value: { space: 'hex', value: '#00883c' } },
        { name: 'green-40', token: '--wa-color-green-40', value: { space: 'hex', value: '#036730' } },
        { name: 'green-30', token: '--wa-color-green-30', value: { space: 'hex', value: '#0a5027' } },
        { name: 'green-20', token: '--wa-color-green-20', value: { space: 'hex', value: '#0a3a1d' } },
        { name: 'green-10', token: '--wa-color-green-10', value: { space: 'hex', value: '#052310' } },
        { name: 'green-05', token: '--wa-color-green-05', value: { space: 'hex', value: '#031608' } },
      ],
    },
    {
      name: 'Cyan',
      swatches: [
        { name: 'cyan-95', token: '--wa-color-cyan-95', value: { space: 'hex', value: '#e3f6fb' } },
        { name: 'cyan-90', token: '--wa-color-cyan-90', value: { space: 'hex', value: '#c5ecf7' } },
        { name: 'cyan-80', token: '--wa-color-cyan-80', value: { space: 'hex', value: '#7fd6ec' } },
        { name: 'cyan-70', token: '--wa-color-cyan-70', value: { space: 'hex', value: '#2fbedc' } },
        { name: 'cyan-60', token: '--wa-color-cyan-60', value: { space: 'hex', value: '#00a3c0' } },
        { name: 'cyan-50', token: '--wa-color-cyan-50', value: { space: 'hex', value: '#078098' } },
        { name: 'cyan-40', token: '--wa-color-cyan-40', value: { space: 'hex', value: '#026274' } },
        { name: 'cyan-30', token: '--wa-color-cyan-30', value: { space: 'hex', value: '#014c5b' } },
        { name: 'cyan-20', token: '--wa-color-cyan-20', value: { space: 'hex', value: '#003844' } },
        { name: 'cyan-10', token: '--wa-color-cyan-10', value: { space: 'hex', value: '#002129' } },
        { name: 'cyan-05', token: '--wa-color-cyan-05', value: { space: 'hex', value: '#00151b' } },
      ],
    },
    {
      name: 'Blue',
      swatches: [
        { name: 'blue-95', token: '--wa-color-blue-95', value: { space: 'hex', value: '#e8f3ff' } },
        { name: 'blue-90', token: '--wa-color-blue-90', value: { space: 'hex', value: '#d1e8ff' } },
        { name: 'blue-80', token: '--wa-color-blue-80', value: { space: 'hex', value: '#9fceff' } },
        { name: 'blue-70', token: '--wa-color-blue-70', value: { space: 'hex', value: '#6eb3ff' } },
        { name: 'blue-60', token: '--wa-color-blue-60', value: { space: 'hex', value: '#3e96ff' } },
        { name: 'blue-50', token: '--wa-color-blue-50', value: { space: 'hex', value: '#0071ec' } },
        { name: 'blue-40', token: '--wa-color-blue-40', value: { space: 'hex', value: '#0053c0' } },
        { name: 'blue-30', token: '--wa-color-blue-30', value: { space: 'hex', value: '#003f9c' } },
        { name: 'blue-20', token: '--wa-color-blue-20', value: { space: 'hex', value: '#002d77' } },
        { name: 'blue-10', token: '--wa-color-blue-10', value: { space: 'hex', value: '#001a4e' } },
        { name: 'blue-05', token: '--wa-color-blue-05', value: { space: 'hex', value: '#000f35' } },
      ],
    },
    {
      name: 'Indigo',
      swatches: [
        { name: 'indigo-95', token: '--wa-color-indigo-95', value: { space: 'hex', value: '#f0f2ff' } },
        { name: 'indigo-90', token: '--wa-color-indigo-90', value: { space: 'hex', value: '#dfe5ff' } },
        { name: 'indigo-80', token: '--wa-color-indigo-80', value: { space: 'hex', value: '#bcc7ff' } },
        { name: 'indigo-70', token: '--wa-color-indigo-70', value: { space: 'hex', value: '#9da9ff' } },
        { name: 'indigo-60', token: '--wa-color-indigo-60', value: { space: 'hex', value: '#808aff' } },
        { name: 'indigo-50', token: '--wa-color-indigo-50', value: { space: 'hex', value: '#6163f2' } },
        { name: 'indigo-40', token: '--wa-color-indigo-40', value: { space: 'hex', value: '#4945cb' } },
        { name: 'indigo-30', token: '--wa-color-indigo-30', value: { space: 'hex', value: '#3933a7' } },
        { name: 'indigo-20', token: '--wa-color-indigo-20', value: { space: 'hex', value: '#292381' } },
        { name: 'indigo-10', token: '--wa-color-indigo-10', value: { space: 'hex', value: '#181255' } },
        { name: 'indigo-05', token: '--wa-color-indigo-05', value: { space: 'hex', value: '#0d0a3a' } },
      ],
    },
    {
      name: 'Purple',
      swatches: [
        { name: 'purple-95', token: '--wa-color-purple-95', value: { space: 'hex', value: '#f7f0ff' } },
        { name: 'purple-90', token: '--wa-color-purple-90', value: { space: 'hex', value: '#eedfff' } },
        { name: 'purple-80', token: '--wa-color-purple-80', value: { space: 'hex', value: '#ddbdff' } },
        { name: 'purple-70', token: '--wa-color-purple-70', value: { space: 'hex', value: '#ca99ff' } },
        { name: 'purple-60', token: '--wa-color-purple-60', value: { space: 'hex', value: '#b678f5' } },
        { name: 'purple-50', token: '--wa-color-purple-50', value: { space: 'hex', value: '#9951db' } },
        { name: 'purple-40', token: '--wa-color-purple-40', value: { space: 'hex', value: '#7936b3' } },
        { name: 'purple-30', token: '--wa-color-purple-30', value: { space: 'hex', value: '#612692' } },
        { name: 'purple-20', token: '--wa-color-purple-20', value: { space: 'hex', value: '#491870' } },
        { name: 'purple-10', token: '--wa-color-purple-10', value: { space: 'hex', value: '#2d0b48' } },
        { name: 'purple-05', token: '--wa-color-purple-05', value: { space: 'hex', value: '#1e0532' } },
      ],
    },
    {
      name: 'Pink',
      swatches: [
        { name: 'pink-95', token: '--wa-color-pink-95', value: { space: 'hex', value: '#feeff9' } },
        { name: 'pink-90', token: '--wa-color-pink-90', value: { space: 'hex', value: '#feddf0' } },
        { name: 'pink-80', token: '--wa-color-pink-80', value: { space: 'hex', value: '#fcb5d8' } },
        { name: 'pink-70', token: '--wa-color-pink-70', value: { space: 'hex', value: '#f78dbf' } },
        { name: 'pink-60', token: '--wa-color-pink-60', value: { space: 'hex', value: '#e66ba3' } },
        { name: 'pink-50', token: '--wa-color-pink-50', value: { space: 'hex', value: '#c84382' } },
        { name: 'pink-40', token: '--wa-color-pink-40', value: { space: 'hex', value: '#9e2a6c' } },
        { name: 'pink-30', token: '--wa-color-pink-30', value: { space: 'hex', value: '#7d1e58' } },
        { name: 'pink-20', token: '--wa-color-pink-20', value: { space: 'hex', value: '#5e1342' } },
        { name: 'pink-10', token: '--wa-color-pink-10', value: { space: 'hex', value: '#3c0828' } },
        { name: 'pink-05', token: '--wa-color-pink-05', value: { space: 'hex', value: '#28041a' } },
      ],
    },
    {
      name: 'Gray',
      swatches: [
        { name: 'gray-95', token: '--wa-color-gray-95', value: { space: 'hex', value: '#f1f2f3' } },
        { name: 'gray-90', token: '--wa-color-gray-90', value: { space: 'hex', value: '#e4e5e9' } },
        { name: 'gray-80', token: '--wa-color-gray-80', value: { space: 'hex', value: '#c7c9d0' } },
        { name: 'gray-70', token: '--wa-color-gray-70', value: { space: 'hex', value: '#abaeb9' } },
        { name: 'gray-60', token: '--wa-color-gray-60', value: { space: 'hex', value: '#9194a2' } },
        { name: 'gray-50', token: '--wa-color-gray-50', value: { space: 'hex', value: '#717584' } },
        { name: 'gray-40', token: '--wa-color-gray-40', value: { space: 'hex', value: '#545868' } },
        { name: 'gray-30', token: '--wa-color-gray-30', value: { space: 'hex', value: '#424554' } },
        { name: 'gray-20', token: '--wa-color-gray-20', value: { space: 'hex', value: '#2f323f' } },
        { name: 'gray-10', token: '--wa-color-gray-10', value: { space: 'hex', value: '#1b1d26' } },
        { name: 'gray-05', token: '--wa-color-gray-05', value: { space: 'hex', value: '#101219' } },
      ],
    },
  ],
} satisfies Palette
